// The educational DNA. Each topic is a short "explore" (2–3 min) that helps
// people think DIFFERENTLY about money — grounded in the financial-planning
// curriculum's philosophy (chapter references), not its wording.
// Educational only: no product, investment, insurance, tax, or legal advice.

export const topicsContent = {
  en: {
    order: ['cashflow', 'insurance', 'retirement', 'education', 'estate', 'tax', 'investing', 'stress', 'risk'],
    ui: {
      instead: 'A common way to think',
      understand: 'A more useful way to see it',
      beatLabels: { idea: 'The bigger idea', behavior: 'Behavioral insight', myth: 'Common misconception', example: 'In real life', did: 'Did you know' },
      mythLabel: 'The myth', truthLabel: 'Closer to the truth',
      groundedIn: 'Grounded in', chapter: 'Chapter',
      start: 'Start exploring', next: 'Next', prev: 'Back', finish: 'Finish', of: 'of', minutes: 'min',
      takeawayLabel: 'Take this with you', stepLabel: 'One small step', learnedLabel: 'What you took away',
      doneTitle: 'Nicely done.', doneBody: "That's now part of your roadmap. Explore another whenever you like — the Hub is always here.",
      addedNote: 'Added to your roadmap', backToHub: 'Back to the Hub', exploreAnother: 'Explore another topic',
    },
    topics: {
      cashflow: {
        icon: 'Coins', ch: '3', chTitle: 'Cash Flow & Net Worth Planning',
        title: 'Cash Flow', tagline: 'Why seeing your money is more powerful than restricting it.', minutes: 3,
        reframe: { from: 'A budget means restricting myself.', to: 'Cash flow is the story of my choices — and seeing it clearly is the real lever.' },
        beats: [
          { kind: 'idea', title: 'It all starts here', body: 'Almost every financial plan begins by looking at cash flow and net worth — not to grade you, but to find your strengths and the one or two gaps worth working on. Money flows in, flows out, and pools into what you own. Seeing that flow is the quiet engine behind every goal.' },
          { kind: 'behavior', title: 'Attention, not willpower', body: 'We notice income far more than we notice spending. Simply watching where money goes tends to reduce it — attention is the active ingredient, not discipline. That is why "just track it for a week" works better than any strict rule.' },
          { kind: 'myth', myth: 'A budget is about denying yourself.', truth: "A budget is just a plan for money you'd spend anyway. Done well, it's permission — it tells you what you can enjoy without worry." },
          { kind: 'example', body: 'Two people earn the same. One keeps a small, named surplus each month; the other lets it drift. Years later the first has a cushion, a trip, a down payment. The difference was never income — it was flow, made visible.' },
          { kind: 'did', body: 'Planners call the money you can redirect your "discretionary cash flow." Even small amounts, moved on purpose, compound into the things you actually care about.' },
        ],
        takeaway: { title: 'You can start with a look, not a spreadsheet.', step: 'This week, just notice where your money actually goes. Awareness is step one of every plan.' },
      },
      insurance: {
        icon: 'Umbrella', ch: '5–9', chTitle: 'Insurance & Risk Management',
        title: 'Insurance Awareness', tagline: 'Why coverage is about the losses you couldn\u2019t absorb — and why it changes as life changes.', minutes: 3,
        reframe: { from: 'Insurance protects against risk.', to: 'Insurance is for the losses I couldn\u2019t recover from on my own — and that set shifts as life shifts.' },
        beats: [
          { kind: 'idea', title: 'One honest question', body: 'Risk management asks a single question: which losses could you not recover from yourself? Insurance exists to transfer exactly those — not every little risk, just the ones that could genuinely undo you.' },
          { kind: 'behavior', title: 'Our instincts run backwards', body: 'We tend to insure what scares us (small, frequent annoyances) and underinsure what could ruin us (rare, large events). Good coverage is often the opposite of our gut — it protects against the catastrophe, not the inconvenience.' },
          { kind: 'myth', myth: 'Once I have insurance, I\u2019m set.', truth: 'Coverage should be reviewed as life changes. A new child, a home, a job, a move — each can quietly open a gap you didn\u2019t have last year.' },
          { kind: 'example', body: 'A policy that fit perfectly at 25 — single, renting — rarely fits at 35 with a home, a child, and a mortgage. Nothing went wrong; life simply changed what a loss would cost.' },
          { kind: 'did', body: 'For a typical working adult, becoming disabled in a given year is more likely than dying — yet disability coverage is one of the most overlooked protections there is.' },
        ],
        takeaway: { title: 'Understanding beats buying.', step: 'Find one policy you already have and read what it actually covers. Knowing your protection is protection in itself.' },
      },
      retirement: {
        icon: 'Clock', ch: '12', chTitle: 'Retirement Planning',
        title: 'Retirement Readiness', tagline: 'Why time is usually worth more than finding the perfect investment.', minutes: 3,
        reframe: { from: 'Retirement grows through clever investing.', to: 'Time does the heavy lifting — starting matters more than being perfect.' },
        beats: [
          { kind: 'idea', title: 'A three-legged table', body: 'Retirement is often pictured as a three-legged table: Social Security, workplace plans, and personal savings. A stable retirement isn\u2019t one brilliant move — it\u2019s knowing which legs you have and slowly building them.' },
          { kind: 'behavior', title: 'Waiting for perfect', body: 'We wait for certainty — the right amount, the right fund, the right moment. But the biggest driver of retirement outcomes isn\u2019t cleverness; it\u2019s years. Starting small nearly always beats starting perfectly.' },
          { kind: 'myth', myth: 'I need a lot of money, or expertise, to begin.', truth: 'Time is the real engine. A modest amount started early can quietly outgrow a large amount started late — because it has more years to grow on itself.' },
          { kind: 'example', body: 'Two savers set aside the same total over their lives. The one who started ten years earlier — with smaller contributions — often ends up ahead, purely because their money had longer to compound.' },
          { kind: 'did', body: 'This is why planners say "time in the market, not timing the market." The reliable lever is how long you\u2019re invested, not how shrewd your picks are.' },
        ],
        takeaway: { title: 'The best day to start is the day you start.', step: 'Find out what retirement option, if any, is available to you — and how it works. Knowing is the beginning.' },
      },
      education: {
        icon: 'GraduationCap', ch: '11', chTitle: 'Education Planning',
        title: 'Education Planning', tagline: 'Why funding a child\u2019s future works best when it doesn\u2019t borrow from your own.', minutes: 3,
        reframe: { from: 'Save for the kids\u2019 college above all else.', to: 'Education is one goal among several — the art is balancing it with your own foundation.' },
        beats: [
          { kind: 'idea', title: 'Goals share the stage', body: 'Education planning isn\u2019t separate from the rest of your money — it competes and cooperates with retirement, cash flow, and taxes. The skill is funding a child\u2019s future without quietly borrowing from your own.' },
          { kind: 'behavior', title: 'Love can skew the order', body: 'Out of love, parents often put education ahead of their own retirement. But there\u2019s a hard truth worth remembering: you can borrow for education — you cannot borrow for retirement.' },
          { kind: 'myth', myth: 'I should fully fund college before anything else.', truth: 'Your own foundation — a cushion and steady retirement saving — usually comes first. A financially stable parent is itself a gift to a child.' },
          { kind: 'example', body: 'A family pours everything into a college fund, then meets a job loss with no cushion. The lesson isn\u2019t "don\u2019t save for school" — it\u2019s "keep the goals in balance."' },
          { kind: 'did', body: 'Dedicated education accounts often carry tax advantages, but the biggest win is the same as any long-horizon goal: starting early and steadily.' },
        ],
        takeaway: { title: 'A timeline turns worry into a plan.', step: 'If education is a goal, write down roughly when you\u2019ll need the money. Even a rough horizon changes how you save.' },
      },
      estate: {
        icon: 'Scroll', ch: '13', chTitle: 'Estate Planning',
        title: 'Estate Readiness', tagline: 'Why it\u2019s really about who acts for you if you can\u2019t — not just who inherits.', minutes: 3,
        reframe: { from: 'Estate planning is for the wealthy, and for after death.', to: 'It\u2019s deciding who acts for me if I can\u2019t — for everyone, starting now.' },
        beats: [
          { kind: 'idea', title: 'Care and clarity', body: 'Estate planning answers two very human questions: who manages things for you if you\u2019re incapacitated, and how your wishes are honored later. It\u2019s less about wealth than about care and clarity for the people you love.' },
          { kind: 'behavior', title: 'We avoid what we fear', body: 'We put it off because it touches mortality. But that avoidance is exactly what leaves loved ones with confusion at the hardest possible moment.' },
          { kind: 'myth', myth: 'Estate planning is only for rich people.', truth: 'Anyone with people they care about — or decisions they\u2019d want honored — benefits from a few basic documents. It starts with naming who decides for you.' },
          { kind: 'example', body: 'An unexpected illness leaves a family unsure who can make medical or financial decisions. A simple document, made earlier, would have spared them the scramble at the worst time.' },
          { kind: 'did', body: 'Core estate planning often begins not with inheritance, but with naming who makes health and money decisions for you if you can\u2019t make them yourself.' },
        ],
        takeaway: { title: 'Clarity is a gift to your people.', step: 'Note one wish you\u2019d want honored, and one person you\u2019d trust to carry it out. That\u2019s a real beginning.' },
      },
      tax: {
        icon: 'Receipt', ch: '4', chTitle: 'Income Tax Planning',
        title: 'Tax Readiness', tagline: 'Why tax awareness quietly increases the money you keep — all year, not just in April.', minutes: 3,
        reframe: { from: 'Taxes are an April chore I can\u2019t influence.', to: 'Tax awareness is a year-round lever on the money I actually keep.' },
        beats: [
          { kind: 'idea', title: 'It follows your cash flow', body: 'Tax planning flows naturally from your cash flow — and it\u2019s an educational tool, not just a filing. Understanding how choices are taxed reveals ways to keep more of what you earn, without any tricks.' },
          { kind: 'behavior', title: 'A once-a-year illusion', body: 'We treat taxes as a single spring event we can\u2019t affect. But many everyday choices — how you save, when you contribute — carry tax ripples you can actually steer during the year.' },
          { kind: 'myth', myth: 'A big refund means I did well.', truth: 'A refund is often just your own money returned to you late. The goal isn\u2019t a spring surprise — it\u2019s steady awareness through the year.' },
          { kind: 'example', body: 'Choosing a pre-tax retirement contribution can lower this year\u2019s taxable income and free up cash flow — a single decision that touches retirement, cash flow, and taxes at once.' },
          { kind: 'did', body: 'Planners sequence taxes right after cash flow because one recommendation often ripples across all three. The lever is awareness, not loopholes.' },
        ],
        takeaway: { title: 'Small understanding, steady payoff.', step: 'Learn one thing about how your own income is taxed. (This is educational — not tax advice.)' },
      },
      investing: {
        icon: 'TrendingUp', ch: '10', chTitle: 'Investment Planning',
        title: 'Investment Fundamentals', tagline: 'Why matching risk to who you are beats chasing the perfect pick.', minutes: 3,
        reframe: { from: 'Good investing means picking winners.', to: 'Good investing means a plan I can actually stick with — matched to who I am.' },
        beats: [
          { kind: 'idea', title: 'Art and system', body: 'Investing is as much art as system: it blends the numbers with your own temperament. The core isn\u2019t a hot pick — it\u2019s the risk-return tradeoff and choosing a level of risk you can genuinely live with.' },
          { kind: 'behavior', title: 'Our instincts betray us', body: 'We tend to buy after things rise and sell after they fall — the opposite of the plan. Knowing your own reactions is more protective than any forecast.' },
          { kind: 'myth', myth: 'Good investing means beating the market.', truth: 'For most people, good investing means a plan they can hold through the ups and downs. Consistency, not brilliance, is what compounds.' },
          { kind: 'example', body: 'Two investors hold the exact same portfolio; one panic-sells in a dip, the other simply waits. Same investments, very different outcomes — behavior decided it, not cleverness.' },
          { kind: 'did', body: 'Higher potential return comes bundled with higher risk — that\u2019s the tradeoff, not a flaw. How comfortable you are with it is personal, and worth knowing. (Educational — not investment advice.)' },
        ],
        takeaway: { title: 'Your reactions are real data.', step: 'Notice how you\u2019d feel if your savings dropped 20% on paper. That feeling tells you something true about your risk comfort.' },
      },
      stress: {
        icon: 'Heart', ch: '1', chTitle: 'The Financial Planning Process',
        title: 'Financial Stress', tagline: 'Why money stress is information — and easing it is part of the plan, not separate from it.', minutes: 3,
        reframe: { from: 'I just need to stop worrying about money.', to: 'Money stress is a signal — and planning is a behavioral practice, not only math.' },
        beats: [
          { kind: 'idea', title: 'A behavioral practice', body: 'Financial planning began as, and remains, a force for behavioral change in people\u2019s lives. Money stress isn\u2019t a character flaw or a math error — it\u2019s a signal, and easing it is part of the plan, not a distraction from it.' },
          { kind: 'behavior', title: 'The worry loop', body: 'Stress narrows attention to right now, which makes long-term choices harder — a loop where worry feeds avoidance and avoidance feeds more worry. Naming the worry is what loosens the loop.' },
          { kind: 'myth', myth: 'Financially responsible people don\u2019t feel money stress.', truth: 'Stress tracks uncertainty, not virtue. It eases with clarity and small steps — not with self-blame.' },
          { kind: 'example', body: 'Someone dreads opening their bills, so the unopened envelope grows scarier than the bill inside. Opening one and naming the actual number shrinks it back to something manageable.' },
          { kind: 'did', body: 'Behavioral research finds that simply naming an emotion measurably lowers its intensity — an effect called "affect labeling." Clarity itself is a form of relief.' },
        ],
        takeaway: { title: 'Naming is the first, freeing step.', step: 'Name the one money worry that\u2019s loudest — out loud or on paper. You don\u2019t have to carry it silently.' },
      },
      risk: {
        icon: 'Scale', ch: '10', chTitle: 'Investment Planning',
        title: 'Financial Risk Comfort', tagline: 'Why knowing your own comfort with risk matters more than hitting some target.', minutes: 3,
        reframe: { from: 'I should take more risk to grow my money.', to: 'The right risk level is the one that fits me — cautious and bold can both succeed.' },
        beats: [
          { kind: 'idea', title: 'Self-knowledge, not a target', body: 'Risk comfort is a personal trait, shaped by temperament and experience — neither good nor bad. A plan built around who you actually are is one you can hold onto when things get bumpy.' },
          { kind: 'behavior', title: 'We learn it in the downturn', body: 'Our stated comfort with risk and our real reactions often differ. Many people discover their true tolerance only in a downturn — far better to reflect on it before, not during.' },
          { kind: 'myth', myth: 'More comfortable with risk means better with money.', truth: 'The best risk level is the one that lets you sleep and stay the course. Cautious investors and bold ones both reach their goals — mismatch is what derails plans.' },
          { kind: 'example', body: 'A cautious saver and a bold investor both arrive at their goals — because each chose a path that matched them and stuck with it. It wasn\u2019t the risk level that mattered, but the fit.' },
          { kind: 'did', body: 'Planners weigh your risk tolerance alongside the numbers, because personal characteristics shape financial decisions as much as returns do. Knowing yourself is genuine data.' },
        ],
        takeaway: { title: 'This is about fit, not pressure.', step: 'There\u2019s no nudge here to take more or less risk — just to know your own comfort, so your choices can fit you.' },
      },
    },
  },

  ko: {
    order: ['cashflow', 'insurance', 'retirement', 'education', 'estate', 'tax', 'investing', 'stress', 'risk'],
    ui: {
      instead: '흔한 생각',
      understand: '더 쓸모 있는 관점',
      beatLabels: { idea: '더 큰 그림', behavior: '행동 인사이트', myth: '흔한 오해', example: '현실에서는', did: '알고 계셨나요' },
      mythLabel: '오해', truthLabel: '진실에 더 가까운 것',
      groundedIn: '근거', chapter: '챕터',
      start: '탐색 시작', next: '다음', prev: '이전', finish: '마치기', of: '중', minutes: '분',
      takeawayLabel: '가져갈 것', stepLabel: '작은 한 걸음', learnedLabel: '오늘 가져가는 것',
      doneTitle: '멋져요.', doneBody: '이제 로드맵의 일부가 되었어요. 원할 때 언제든 다른 주제를 탐색해 보세요 — 허브는 늘 여기 있어요.',
      addedNote: '로드맵에 추가됨', backToHub: '허브로 돌아가기', exploreAnother: '다른 주제 탐색하기',
    },
    topics: {
      cashflow: {
        icon: 'Coins', ch: '3', chTitle: '현금흐름과 순자산 설계',
        title: '현금 흐름', tagline: '억누르기보다, 내 돈을 보는 것이 더 강력한 이유.', minutes: 3,
        reframe: { from: '예산은 나를 억누르는 것.', to: '현금 흐름은 내 선택의 이야기이고, 그걸 또렷이 보는 것이 진짜 지렛대다.' },
        beats: [
          { kind: 'idea', title: '모든 게 여기서 시작돼요', body: '거의 모든 재무 계획은 현금 흐름과 순자산을 보는 데서 시작해요 — 당신을 판단하려는 게 아니라, 강점과 손볼 만한 한두 가지 빈틈을 찾으려는 거죠. 돈은 들어오고, 나가고, 소유한 것으로 고여요. 그 흐름을 보는 것이 모든 목표 뒤의 조용한 엔진이에요.' },
          { kind: 'behavior', title: '의지력이 아니라 주의', body: '우리는 지출보다 수입을 훨씬 더 의식해요. 돈이 어디로 가는지 지켜보기만 해도 지출이 줄어드는 경향이 있죠 — 규율이 아니라 주의가 핵심 성분이에요. 그래서 엄격한 규칙보다 "일주일만 적어 보기"가 더 잘 통합니다.' },
          { kind: 'myth', myth: '예산은 나를 참게 만드는 것.', truth: '예산은 어차피 쓸 돈에 대한 계획일 뿐이에요. 잘 세우면 오히려 허락이 됩니다 — 걱정 없이 무엇을 즐겨도 되는지 알려 주니까요.' },
          { kind: 'example', body: '두 사람이 같은 돈을 벌어요. 한 사람은 매달 작은, 이름 붙인 여유를 남기고, 다른 사람은 흘려보내요. 몇 해 뒤 앞 사람에겐 비상금, 여행, 계약금이 생깁니다. 차이는 수입이 아니라, 보이게 만든 흐름이었어요.' },
          { kind: 'did', body: '설계사들은 당신이 옮길 수 있는 돈을 "가용 현금흐름"이라 불러요. 작은 금액도 의도적으로 옮기면, 정말 소중한 것들로 쌓여 갑니다.' },
        ],
        takeaway: { title: '스프레드시트가 아니라, 보는 것에서 시작해요.', step: '이번 주엔 그저 돈이 실제로 어디로 가는지 살펴보세요. 알아차림이 모든 계획의 첫걸음이에요.' },
      },
      insurance: {
        icon: 'Umbrella', ch: '5–9', chTitle: '보험과 위험관리',
        title: '보험 이해', tagline: '보험은 스스로 감당 못 할 손실을 위한 것 — 삶이 변하면 함께 변해야 하는 이유.', minutes: 3,
        reframe: { from: '보험은 위험을 막아 주는 것.', to: '보험은 내가 스스로 회복할 수 없는 손실을 위한 것 — 그 목록은 삶과 함께 변한다.' },
        beats: [
          { kind: 'idea', title: '하나의 정직한 질문', body: '위험관리는 한 가지 질문을 던져요: 어떤 손실은 스스로 회복할 수 없는가? 보험은 바로 그런 손실을 넘기려 존재해요 — 사소한 위험 전부가 아니라, 당신을 정말 무너뜨릴 수 있는 것들이요.' },
          { kind: 'behavior', title: '본능은 거꾸로 가요', body: '우리는 무서운 것(작고 잦은 성가심)엔 보험을 들고, 파멸적인 것(드물고 큰 사건)엔 보험이 부족한 경향이 있어요. 좋은 보장은 대개 직감의 반대예요 — 불편이 아니라 재앙을 막죠.' },
          { kind: 'myth', myth: '보험 하나 들었으면 끝.', truth: '보장은 삶이 변할 때 다시 살펴봐야 해요. 아이, 집, 직장, 이사 — 하나하나가 작년엔 없던 빈틈을 조용히 열 수 있어요.' },
          { kind: 'example', body: '25살 미혼·전세 때 딱 맞던 보험이, 집과 아이와 대출이 있는 35살엔 잘 맞지 않아요. 잘못된 게 아니라, 손실의 크기를 삶이 바꿔 놓은 거죠.' },
          { kind: 'did', body: '평범한 직장인에게 어느 해에 장애를 겪을 확률은 이른 사망 확률보다 높아요 — 그런데도 장애 보장은 가장 간과되는 보호 중 하나죠.' },
        ],
        takeaway: { title: '이해가 가입을 이겨요.', step: '이미 가진 보험 하나를 찾아, 무엇을 보장하는지 읽어 보세요. 내 보호를 아는 것 자체가 보호예요.' },
      },
      retirement: {
        icon: 'Clock', ch: '12', chTitle: '은퇴 설계',
        title: '은퇴 준비', tagline: '완벽한 투자를 찾기보다, 시간이 대개 더 값진 이유.', minutes: 3,
        reframe: { from: '은퇴는 영리한 투자로 커진다.', to: '무거운 일은 시간이 해낸다 — 완벽함보다 시작이 더 중요하다.' },
        beats: [
          { kind: 'idea', title: '세 다리 탁자', body: '은퇴는 흔히 세 다리 탁자로 그려져요: 공적연금, 직장 제도, 개인 저축. 안정적인 은퇴는 한 번의 명수가 아니라, 어떤 다리를 가졌는지 알고 천천히 쌓는 일이에요.' },
          { kind: 'behavior', title: '완벽을 기다리기', body: '우리는 확신을 기다려요 — 알맞은 금액, 알맞은 상품, 알맞은 시점. 하지만 은퇴 결과의 가장 큰 동력은 영리함이 아니라 세월이에요. 작게 시작하는 게 완벽하게 시작하는 것을 거의 늘 이깁니다.' },
          { kind: 'myth', myth: '시작하려면 큰돈이나 전문성이 필요해.', truth: '진짜 엔진은 시간이에요. 일찍 시작한 적은 돈이, 늦게 시작한 큰돈을 조용히 앞설 수 있어요 — 스스로 불어날 세월이 더 많으니까요.' },
          { kind: 'example', body: '두 사람이 평생 같은 총액을 모아요. 10년 먼저 시작한 사람이 — 매번 더 적게 넣고도 — 대개 앞서요. 오직 그 돈이 복리로 자랄 시간이 더 길었기 때문이죠.' },
          { kind: 'did', body: '그래서 설계사들은 "타이밍이 아니라 시장에 머문 시간"이라고 해요. 믿을 만한 지렛대는 얼마나 영리하냐가 아니라 얼마나 오래냐예요.' },
        ],
        takeaway: { title: '시작하기 가장 좋은 날은, 시작하는 날.', step: '나에게 어떤 은퇴 제도가 있는지, 어떻게 작동하는지 알아보세요. 아는 것이 시작이에요.' },
      },
      education: {
        icon: 'GraduationCap', ch: '11', chTitle: '교육 설계',
        title: '교육 설계', tagline: '아이의 미래를, 내 미래에서 빌려오지 않고 마련하는 법.', minutes: 3,
        reframe: { from: '무엇보다 아이 학자금을 먼저.', to: '교육은 여러 목표 중 하나 — 핵심은 내 토대와의 균형이다.' },
        beats: [
          { kind: 'idea', title: '목표들은 무대를 나눠 써요', body: '교육 설계는 나머지 재정과 별개가 아니라 은퇴·현금흐름·세금과 경쟁하고 협력해요. 요령은 내 미래에서 조용히 빌려오지 않으면서 아이의 미래를 마련하는 거예요.' },
          { kind: 'behavior', title: '사랑이 순서를 흔들어요', body: '사랑으로, 부모는 흔히 자신의 은퇴보다 교육을 앞세워요. 하지만 기억할 냉정한 사실이 있어요: 교육은 빌릴 수 있어도, 은퇴는 빌릴 수 없어요.' },
          { kind: 'myth', myth: '무엇보다 학자금부터 다 채워야 해.', truth: '대개 내 토대 — 비상금과 꾸준한 은퇴 저축 — 가 먼저예요. 재정적으로 안정된 부모 자체가 아이에게 선물이거든요.' },
          { kind: 'example', body: '한 가정이 학자금에 모든 걸 쏟다가, 완충 없이 실직을 만나요. 교훈은 "학자금을 모으지 말라"가 아니라 "목표의 균형을 지켜라"예요.' },
          { kind: 'did', body: '전용 교육 계좌엔 세제 혜택이 있는 경우가 많지만, 가장 큰 이점은 다른 장기 목표와 같아요: 일찍, 꾸준히 시작하는 것.' },
        ],
        takeaway: { title: '기한이 걱정을 계획으로 바꿔요.', step: '교육이 목표라면, 언제쯤 돈이 필요할지 대략 적어 보세요. 대략의 기한만으로도 저축 방식이 달라져요.' },
      },
      estate: {
        icon: 'Scroll', ch: '13', chTitle: '상속·유산 설계',
        title: '상속 준비', tagline: '누가 상속받느냐보다, 내가 못 할 때 누가 대신 결정하느냐의 문제인 이유.', minutes: 3,
        reframe: { from: '유산 설계는 부자, 그리고 죽은 뒤의 일.', to: '내가 결정할 수 없을 때 누가 나를 대신할지 정하는 일 — 모두에게, 지금부터.' },
        beats: [
          { kind: 'idea', title: '돌봄과 또렷함', body: '유산 설계는 아주 인간적인 두 질문에 답해요: 내가 결정할 수 없게 되면 누가 나를 대신 관리하는가, 그리고 내 뜻이 나중에 어떻게 존중되는가. 재산보다 사랑하는 이들을 위한 돌봄과 또렷함에 관한 일이죠.' },
          { kind: 'behavior', title: '두려운 것을 미뤄요', body: '죽음을 건드리기에 우리는 미뤄요. 하지만 바로 그 미룸이, 가장 힘든 순간에 사랑하는 이들을 혼란 속에 남깁니다.' },
          { kind: 'myth', myth: '유산 설계는 부자만의 일.', truth: '아끼는 사람이 있거나, 존중받길 바라는 결정이 있는 사람이라면 누구나 기본 문서로 도움을 받아요. 시작은 "누가 나를 대신 결정할지" 정하는 거예요.' },
          { kind: 'example', body: '갑작스러운 병으로, 가족이 누가 의료·재정 결정을 내릴 수 있는지 몰라 헤매요. 미리 만든 간단한 문서 하나가 그 아수라장을 덜어 줬을 거예요.' },
          { kind: 'did', body: '핵심 유산 설계는 흔히 상속이 아니라, 내가 못 할 때 누가 나의 건강·돈 결정을 내릴지 정하는 데서 시작해요.' },
        ],
        takeaway: { title: '또렷함은 내 사람들에게 주는 선물.', step: '존중받길 바라는 뜻 하나와, 그걸 맡길 만큼 믿는 사람 한 명을 적어 보세요. 그게 진짜 시작이에요.' },
      },
      tax: {
        icon: 'Receipt', ch: '4', chTitle: '소득세 설계',
        title: '세금 준비', tagline: '세금 감각이, 4월뿐 아니라 일 년 내내 내가 지키는 돈을 늘리는 이유.', minutes: 3,
        reframe: { from: '세금은 어쩔 수 없는 4월의 숙제.', to: '세금 감각은 내가 실제로 지키는 돈에 대한 연중 지렛대다.' },
        beats: [
          { kind: 'idea', title: '현금 흐름을 따라와요', body: '세금 설계는 현금 흐름에서 자연스럽게 이어져요 — 그리고 단순한 신고가 아니라 교육 도구예요. 선택이 어떻게 과세되는지 이해하면, 어떤 꼼수 없이도 버는 돈을 더 지키는 길이 보여요.' },
          { kind: 'behavior', title: '연 1회라는 착각', body: '우리는 세금을 손댈 수 없는 봄의 단발 이벤트로 여겨요. 하지만 어떻게 저축하고 언제 납입하느냐 같은 일상의 선택엔, 연중 조절할 수 있는 세금의 파장이 있어요.' },
          { kind: 'myth', myth: '환급이 크면 잘한 거야.', truth: '환급은 대개 내 돈을 늦게 돌려받는 것뿐이에요. 목표는 봄의 깜짝 선물이 아니라, 연중 꾸준한 감각이에요.' },
          { kind: 'example', body: '세전 은퇴 납입을 선택하면 올해 과세소득이 줄고 현금 흐름이 풀릴 수 있어요 — 은퇴·현금흐름·세금을 한 번에 건드리는 하나의 결정이죠.' },
          { kind: 'did', body: '설계사들이 세금을 현금 흐름 바로 뒤에 두는 건, 하나의 권고가 셋 모두로 번지기 때문이에요. 지렛대는 허점이 아니라 감각이에요.' },
        ],
        takeaway: { title: '작은 이해, 꾸준한 보상.', step: '내 소득이 어떻게 과세되는지 한 가지만 배워 보세요. (교육 목적이며, 세무 자문이 아닙니다.)' },
      },
      investing: {
        icon: 'TrendingUp', ch: '10', chTitle: '투자 설계',
        title: '투자 기초', tagline: '완벽한 종목을 쫓기보다, 나에게 맞는 위험을 고르는 것이 이기는 이유.', minutes: 3,
        reframe: { from: '좋은 투자는 승자를 고르는 것.', to: '좋은 투자는 내가 실제로 지킬 수 있는 계획 — 나에게 맞춘 것이다.' },
        beats: [
          { kind: 'idea', title: '기술이자 체계', body: '투자는 체계인 만큼 기술이에요: 숫자와 당신의 기질을 함께 엮죠. 핵심은 뜨거운 종목이 아니라 위험-수익 상충, 그리고 정말로 견딜 수 있는 위험 수준을 고르는 거예요.' },
          { kind: 'behavior', title: '본능이 우리를 배신해요', body: '우리는 오르고 나서 사고, 떨어지고 나서 파는 경향이 있어요 — 계획의 정반대죠. 어떤 예측보다 내 반응을 아는 것이 더 든든해요.' },
          { kind: 'myth', myth: '좋은 투자는 시장을 이기는 것.', truth: '대부분에게 좋은 투자는 오르내림을 견디며 지킬 수 있는 계획이에요. 복리로 쌓이는 건 천재성이 아니라 꾸준함이죠.' },
          { kind: 'example', body: '두 투자자가 똑같은 포트폴리오를 들고 있어요; 한 명은 하락에 공포에 팔고, 한 명은 그냥 기다려요. 같은 투자, 아주 다른 결과 — 영리함이 아니라 행동이 갈랐어요.' },
          { kind: 'did', body: '더 큰 잠재 수익엔 더 큰 위험이 함께 묶여 있어요 — 결함이 아니라 상충이에요. 그걸 얼마나 편히 받아들이는지는 사람마다 다르고, 알아 둘 가치가 있어요. (교육 목적이며, 투자 자문이 아닙니다.)' },
        ],
        takeaway: { title: '내 반응은 진짜 데이터.', step: '내 저축이 서류상 20% 떨어졌을 때 어떤 기분일지 상상해 보세요. 그 기분이 위험 감수 성향에 대한 진짜 정보예요.' },
      },
      stress: {
        icon: 'Heart', ch: '1', chTitle: '재무설계 프로세스',
        title: '재정 스트레스', tagline: '돈 스트레스는 정보이고, 그것을 더는 일이 계획의 일부인 이유.', minutes: 3,
        reframe: { from: '그냥 돈 걱정을 멈춰야 해.', to: '돈 스트레스는 신호 — 계획은 수학만이 아니라 행동의 실천이다.' },
        beats: [
          { kind: 'idea', title: '행동의 실천', body: '재무설계는 사람들의 삶에서 행동을 바꾸는 힘으로 시작했고, 지금도 그래요. 돈 스트레스는 성격 결함이나 계산 실수가 아니라 신호예요 — 그것을 더는 일은 계획을 방해하는 게 아니라 계획의 일부죠.' },
          { kind: 'behavior', title: '걱정의 고리', body: '스트레스는 주의를 지금 이 순간으로 좁혀, 장기 선택을 어렵게 만들어요 — 걱정이 회피를 낳고 회피가 다시 걱정을 낳는 고리죠. 그 고리를 푸는 것은 걱정에 이름을 붙이는 일이에요.' },
          { kind: 'myth', myth: '재정적으로 책임감 있는 사람은 돈 스트레스가 없어.', truth: '스트레스는 미덕이 아니라 불확실성을 따라와요. 자책이 아니라 또렷함과 작은 걸음으로 누그러집니다.' },
          { kind: 'example', body: '누군가는 청구서 여는 게 두려워, 뜯지 않은 봉투가 그 안의 금액보다 더 무서워져요. 하나를 열어 실제 숫자에 이름을 붙이면, 감당할 만한 크기로 줄어들어요.' },
          { kind: 'did', body: '행동 연구는 감정에 이름을 붙이기만 해도 그 강도가 측정 가능하게 줄어든다고 해요 — "감정 이름 붙이기"라는 효과죠. 또렷함 자체가 안도예요.' },
        ],
        takeaway: { title: '이름 붙이기가 첫, 홀가분한 걸음.', step: '가장 큰 돈 걱정 하나에 이름을 붙여 보세요 — 소리 내어, 또는 종이에. 혼자 조용히 질 필요 없어요.' },
      },
      risk: {
        icon: 'Scale', ch: '10', chTitle: '투자 설계',
        title: '위험 감수 성향', tagline: '어떤 목표치를 맞추기보다, 내 위험 편안함을 아는 것이 더 중요한 이유.', minutes: 3,
        reframe: { from: '돈을 불리려면 위험을 더 져야 해.', to: '알맞은 위험 수준은 나에게 맞는 것 — 신중함도 과감함도 성공할 수 있다.' },
        beats: [
          { kind: 'idea', title: '목표가 아니라 자기 이해', body: '위험 감수 성향은 기질과 경험이 빚은 개인적 특성이에요 — 좋고 나쁨이 아니죠. 진짜 나에게 맞춘 계획이라야, 흔들릴 때도 붙잡고 갈 수 있어요.' },
          { kind: 'behavior', title: '하락장에서 알게 돼요', body: '말로 하는 위험 편안함과 실제 반응은 자주 달라요. 많은 사람이 진짜 감내력을 하락장에서야 알게 되죠 — 그 와중이 아니라 그 전에 돌아보는 게 훨씬 나아요.' },
          { kind: 'myth', myth: '위험에 편할수록 돈을 잘 다루는 것.', truth: '가장 좋은 위험 수준은 당신이 잠들 수 있고 길을 지킬 수 있는 수준이에요. 신중한 투자자도 과감한 투자자도 목표에 닿아요 — 계획을 무너뜨리는 건 어긋남이죠.' },
          { kind: 'example', body: '신중한 저축가와 과감한 투자자가 둘 다 목표에 도달해요 — 각자 자신에게 맞는 길을 골라 지켰으니까요. 중요한 건 위험 수준이 아니라 맞음이었어요.' },
          { kind: 'did', body: '설계사들은 숫자와 함께 당신의 위험 감내력을 저울에 올려요. 개인적 특성이 수익만큼이나 재정 결정을 좌우하니까요. 자신을 아는 것이 진짜 데이터예요.' },
        ],
        takeaway: { title: '압박이 아니라 맞음의 문제.', step: '위험을 더/덜 지라는 권유는 없어요 — 그저 내 편안함을 알아, 선택이 나에게 맞도록 하자는 거예요.' },
      },
    },
  },
}
