// Learning Center. The ideas behind the topics — behavioral insights, common
// mistakes, FAQ, and did-you-know. Extracted philosophy, not chapter summaries.
export const learningContent = {
  en: {
    eyebrow: 'Learning Center',
    title: 'The ideas behind it all.',
    sub: 'A calm place for the thinking that runs under every topic — why we behave the way we do with money, and how a small shift in view changes everything.',
    labels: { insights: 'Behavioral insights', mistakes: 'Common misconceptions', faq: 'Questions people ask', didyou: 'Did you know', mythLabel: 'The myth', truthLabel: 'Closer to the truth' },
    behavioralInsights: [
      { title: 'Attention beats willpower', body: 'You don\u2019t need iron discipline to spend less — you need to see your spending. Simply watching where money goes tends to reduce it on its own. That\u2019s why "track it for a week" outperforms any strict rule.' },
      { title: 'Losses loom larger than gains', body: 'Losing $100 tends to hurt about twice as much as gaining $100 feels good. This is why a safety net matters more than it looks on paper — it protects you from a pain that\u2019s outsized, not just from a number.' },
      { title: 'We discount our future selves', body: 'Given the choice, we favor now over later — which is why good intentions fade. The fix isn\u2019t more willpower; it\u2019s a small automatic default (a transfer on payday) that quietly acts on your behalf.' },
      { title: 'Naming a feeling calms it', body: 'Research on "affect labeling" finds that putting a worry into words measurably lowers its intensity. Money stress shrinks when it\u2019s named and looked at — clarity itself is relief.' },
      { title: 'We sort money into mental buckets', body: 'A dollar in "savings" feels different from a dollar in "spending," even though they\u2019re identical. You can use this on purpose: name an account for what it\u2019s for, and it becomes much harder to spend.' },
      { title: 'The default usually wins', body: 'Whatever requires no decision tends to happen. Left to inaction, saving doesn\u2019t occur; made automatic, it does. Design the default once, and you stop relying on motivation every month.' },
    ],
    commonMistakes: [
      { myth: 'A budget means restricting myself.', truth: 'A budget is a plan for money you\u2019d spend anyway — permission, not punishment. It tells you what you can enjoy without worry.' },
      { myth: 'Once I have insurance, I\u2019m set.', truth: 'Coverage should be reviewed as life changes. A child, a home, a new job — each can open a gap you didn\u2019t have last year.' },
      { myth: 'I\u2019ll invest once I understand it better.', truth: 'For long horizons, time in the market usually beats waiting for the perfect moment or the perfect pick. Starting small early tends to win.' },
      { myth: 'Fund the kids\u2019 college before anything else.', truth: 'You can borrow for education; you cannot borrow for retirement. A stable parent is itself a gift — balance the goals.' },
      { myth: 'Estate planning is only for the wealthy.', truth: 'It starts with naming who makes decisions for you if you can\u2019t. Anyone with people they love benefits from a few basic documents.' },
      { myth: 'A big tax refund is a win.', truth: 'A refund is often your own money returned to you late. The goal is steady awareness through the year, not a spring surprise.' },
    ],
    faq: [
      { q: 'Is any of this financial advice?', a: 'No. FinE Companion is purely educational. It never sells products and never recommends specific investments, insurance, tax, or legal strategies. It\u2019s here to help you think — decisions, and personalized advice, belong with you and a professional you trust.' },
      { q: 'How much should an emergency fund be?', a: 'A common guide is three to six months of essential expenses, but the number matters less than the resilience. If that feels far off, start with one week\u2019s worth — the first small cushion is what stops a surprise from becoming debt.' },
      { q: 'Should I pay off debt or save first?', a: 'Often a little of both. A small starter cushion keeps a surprise from creating new debt, while higher-cost debt is usually worth reducing steadily. The point isn\u2019t a rule — it\u2019s not being forced to borrow at the next bump.' },
      { q: 'What\u2019s a good savings rate?', a: 'The best rate is one you\u2019ll actually keep. Consistency matters more than a magic percentage — start where you can, automate it, and raise it a little when things ease. Direction beats perfection.' },
      { q: 'When should I start saving for retirement?', a: 'As early as you can, even in small amounts. Time is the real engine: money started earlier has more years to grow on itself, which usually matters more than the size of each contribution.' },
      { q: 'Do I need a financial planner?', a: 'This is a learning tool, not a substitute for one. A qualified professional can give advice tailored to your full situation. What we can do is help you arrive better prepared, with clearer questions and less fear.' },
      { q: 'Is my information private?', a: 'Yes. Everything you do here stays in your browser, on your device. There are no accounts, no tracking, and nothing is sold or sent anywhere. You can clear it anytime.' },
      { q: 'What does "risk tolerance" really mean?', a: 'It\u2019s your personal comfort with financial ups and downs — shaped by temperament and experience, and neither good nor bad. Knowing yours isn\u2019t a target to hit; it\u2019s self-knowledge that helps your choices fit you.' },
    ],
    didYouKnow: [
      'For a typical working adult, becoming disabled in a given year is more likely than dying — yet disability coverage is among the most overlooked protections.',
      'Retirement is often pictured as a three-legged table: government benefits, workplace plans, and personal savings. Knowing which legs you have is the first step.',
      'Planners often say "time in the market, not timing the market" — because how long you\u2019re invested tends to matter more than when you buy.',
      'Simply tracking your spending tends to reduce it, with no rules required. Attention is the quiet active ingredient.',
      'Naming an emotion measurably lowers its intensity — an effect researchers call "affect labeling." Clarity is a form of relief.',
      'A large tax refund isn\u2019t a bonus — it\u2019s your own money that was withheld and returned to you later, without interest.',
    ],
  },
  ko: {
    eyebrow: '러닝 센터',
    title: '그 뒤에 있는 생각들.',
    sub: '모든 주제 아래 흐르는 생각을 위한 차분한 공간 — 우리가 돈 앞에서 왜 그렇게 행동하는지, 그리고 관점의 작은 변화가 어떻게 모든 걸 바꾸는지.',
    labels: { insights: '행동 인사이트', mistakes: '흔한 오해', faq: '사람들이 묻는 것', didyou: '알고 계셨나요', mythLabel: '오해', truthLabel: '진실에 더 가까운 것' },
    behavioralInsights: [
      { title: '의지력보다 주의가 이겨요', body: '덜 쓰는 데 강철 같은 규율은 필요 없어요 — 필요한 건 내 지출을 보는 것이죠. 돈이 어디로 가는지 지켜보기만 해도 저절로 줄어드는 경향이 있어요. 그래서 엄격한 규칙보다 "일주일 적어 보기"가 더 잘 통해요.' },
      { title: '손실이 이득보다 크게 느껴져요', body: '10만 원을 잃는 아픔은, 10만 원을 얻는 기쁨보다 대략 두 배 크게 느껴져요. 그래서 안전망은 숫자보다 더 중요해요 — 단순한 금액이 아니라, 유난히 큰 고통으로부터 당신을 지켜 주니까요.' },
      { title: '우리는 미래의 나를 깎아내려요', body: '선택을 주면 우리는 나중보다 지금을 택해요 — 그래서 좋은 결심이 흐려지죠. 해법은 더 큰 의지력이 아니라, 나를 대신 조용히 움직이는 작은 자동 설정(월급날 자동이체)이에요.' },
      { title: '감정에 이름을 붙이면 가라앉아요', body: '"감정 이름 붙이기" 연구는 걱정을 말로 옮기면 그 강도가 측정 가능하게 줄어든다고 해요. 돈 스트레스는 이름 붙이고 들여다볼 때 작아져요 — 또렷함 자체가 안도예요.' },
      { title: '우리는 돈을 마음속 칸으로 나눠요', body: '"저축"의 만 원과 "지출"의 만 원은 똑같은데도 다르게 느껴져요. 이걸 의도적으로 쓸 수 있어요: 계좌에 용도의 이름을 붙이면, 쓰기가 훨씬 어려워집니다.' },
      { title: '대개 기본값이 이겨요', body: '결정이 필요 없는 쪽이 일어나기 마련이에요. 가만두면 저축은 안 되고, 자동으로 만들면 됩니다. 기본값을 한 번 설계해 두면, 매달 의욕에 기대지 않아도 돼요.' },
    ],
    commonMistakes: [
      { myth: '예산은 나를 억누르는 것.', truth: '예산은 어차피 쓸 돈에 대한 계획 — 벌이 아니라 허락이에요. 걱정 없이 무엇을 즐겨도 되는지 알려 주죠.' },
      { myth: '보험 하나 들었으면 끝.', truth: '보장은 삶이 변할 때 다시 봐야 해요. 아이, 집, 새 직장 — 하나하나가 작년엔 없던 빈틈을 열 수 있어요.' },
      { myth: '더 잘 알게 되면 투자할게.', truth: '장기라면, 완벽한 시점이나 종목을 기다리기보다 시장에 머문 시간이 대개 이겨요. 일찍 작게 시작하는 쪽이 이기곤 하죠.' },
      { myth: '무엇보다 아이 학자금부터.', truth: '교육은 빌릴 수 있어도 은퇴는 빌릴 수 없어요. 안정된 부모 자체가 선물이에요 — 목표의 균형을 지키세요.' },
      { myth: '유산 설계는 부자만의 일.', truth: '내가 못 할 때 누가 나를 대신 결정할지 정하는 데서 시작해요. 아끼는 사람이 있는 누구에게나 기본 문서가 도움이 돼요.' },
      { myth: '큰 세금 환급은 이득.', truth: '환급은 대개 내 돈을 늦게 돌려받는 것뿐이에요. 목표는 봄의 깜짝 선물이 아니라 연중 꾸준한 감각이에요.' },
    ],
    faq: [
      { q: '이건 재무 자문인가요?', a: '아니에요. FinE 컴패니언은 순수하게 교육 목적이에요. 상품을 팔지 않고, 특정 투자·보험·세무·법률 전략을 권하지도 않아요. 생각을 돕기 위한 것이며 — 결정과 맞춤 조언은 당신, 그리고 당신이 신뢰하는 전문가의 몫이에요.' },
      { q: '비상금은 얼마여야 하나요?', a: '흔한 기준은 필수 지출의 3~6개월치지만, 금액보다 회복력이 중요해요. 그게 멀게 느껴지면 일주일치부터 시작하세요 — 첫 작은 완충이 뜻밖의 일을 빚으로 만들지 않게 막아 줘요.' },
      { q: '빚을 갚을까요, 저축을 먼저 할까요?', a: '대개 둘 다 조금씩이에요. 작은 시작 완충은 뜻밖의 일이 새 빚이 되는 걸 막고, 이자 높은 빚은 꾸준히 줄이는 게 보통 나아요. 핵심은 규칙이 아니라, 다음 굴곡에서 빌리지 않아도 되는 상태예요.' },
      { q: '저축률은 얼마가 좋나요?', a: '가장 좋은 비율은 실제로 지킬 수 있는 비율이에요. 마법의 퍼센트보다 꾸준함이 중요해요 — 할 수 있는 데서 시작해 자동화하고, 여유가 생기면 조금씩 올리세요. 완벽보다 방향이에요.' },
      { q: '은퇴 저축은 언제 시작하죠?', a: '가능한 한 일찍, 적은 금액이라도요. 진짜 엔진은 시간이에요: 일찍 시작한 돈은 스스로 자랄 세월이 더 많고, 그게 대개 매번의 금액보다 더 중요해요.' },
      { q: '재무 설계사가 필요할까요?', a: '이건 배움의 도구이지 전문가를 대신하진 않아요. 자격 있는 전문가는 당신의 전체 상황에 맞춘 조언을 줄 수 있어요. 우리가 할 수 있는 건, 더 또렷한 질문과 덜한 두려움으로 더 잘 준비되어 가게 돕는 거예요.' },
      { q: '제 정보는 안전한가요?', a: '네. 여기서 하는 모든 건 당신의 브라우저, 당신의 기기 안에 머물러요. 계정도, 추적도 없고, 어디로도 팔리거나 전송되지 않아요. 언제든 지울 수 있어요.' },
      { q: '"위험 감수 성향"이 정확히 뭔가요?', a: '재정의 오르내림에 대한 개인적 편안함이에요 — 기질과 경험이 빚고, 좋고 나쁨이 없죠. 자기 성향을 아는 건 맞춰야 할 목표가 아니라, 선택이 나에게 맞도록 돕는 자기 이해예요.' },
    ],
    didYouKnow: [
      '평범한 직장인에게 어느 해에 장애를 겪을 확률은 이른 사망 확률보다 높아요 — 그런데도 장애 보장은 가장 간과되는 보호 중 하나죠.',
      '은퇴는 흔히 세 다리 탁자로 그려져요: 공적 급여, 직장 제도, 개인 저축. 어떤 다리를 가졌는지 아는 게 첫걸음이에요.',
      '설계사들은 "타이밍이 아니라 시장에 머문 시간"이라고 자주 말해요 — 언제 사느냐보다 얼마나 오래 투자하느냐가 대개 더 중요하니까요.',
      '지출을 적어 보기만 해도 규칙 없이 지출이 줄어드는 경향이 있어요. 주의가 조용한 핵심 성분이에요.',
      '감정에 이름을 붙이면 그 강도가 측정 가능하게 줄어들어요 — 연구자들이 "감정 이름 붙이기"라 부르는 효과죠. 또렷함이 곧 안도예요.',
      '큰 세금 환급은 보너스가 아니라, 원천징수됐다가 이자 없이 나중에 돌려받는 내 돈이에요.',
    ],
  },
}
