// Monthly Check-in. Embodies "life changes, so plans deserve a fresh look."
// Reflective, never advisory. Nothing is scored.
export const checkinContent = {
  en: {
    eyebrow: 'Monthly Check-in',
    title: 'A quiet moment to notice what\u2019s changed.',
    sub: 'Your financial life keeps moving, so it helps to pause now and then. This takes a minute, and there are no wrong answers.',
    prompt: 'Since the last time, has anything shifted?',
    changesHint: 'Tick anything that feels true — or none at all.',
    changes: [
      { id: 'income', label: 'My income changed' },
      { id: 'job', label: 'I started a new job or role' },
      { id: 'home', label: 'I moved, or my housing changed' },
      { id: 'family', label: 'My family changed — a partner, a child, caregiving' },
      { id: 'money', label: 'I took on, or paid off, a big expense or debt' },
      { id: 'health', label: 'My health, or a loved one\u2019s, changed' },
      { id: 'none', label: 'Nothing major — just checking in' },
    ],
    finish: 'Finish check-in',
    changedTitle: 'Thanks for noticing.',
    changedBody: 'When life shifts, the plan that fit before may not fit now — and that\u2019s completely normal. You may find it helpful to revisit your checkup or a topic, so your roadmap keeps pace with your real life.',
    steadyTitle: 'Steady is good.',
    steadyBody: 'Nothing big to report is its own kind of progress. A quick look like this keeps things fresh, so you\u2019re never caught off guard. See you again next month.',
    savedNote: 'Check-in saved',
    seeRoadmap: 'See your roadmap',
    revisitCheckup: 'Revisit the checkup',
    backToHub: 'Back to the Hub',
    lastLabel: 'Last check-in',
  },
  ko: {
    eyebrow: '월간 체크인',
    title: '무엇이 달라졌는지, 조용히 살펴보는 시간.',
    sub: '재정 생활은 계속 움직여요. 그래서 가끔 멈춰 보는 게 도움이 돼요. 1분이면 되고, 틀린 답은 없어요.',
    prompt: '지난번 이후로, 달라진 게 있나요?',
    changesHint: '해당되는 걸 골라 보세요 — 없어도 괜찮아요.',
    changes: [
      { id: 'income', label: '수입이 달라졌어요' },
      { id: 'job', label: '새 직장이나 역할을 시작했어요' },
      { id: 'home', label: '이사했거나 주거가 바뀌었어요' },
      { id: 'family', label: '가족이 달라졌어요 — 배우자, 아이, 돌봄' },
      { id: 'money', label: '큰 지출이나 빚이 생겼거나, 갚았어요' },
      { id: 'health', label: '나 또는 가까운 이의 건강이 달라졌어요' },
      { id: 'none', label: '큰일은 없어요 — 그냥 확인차' },
    ],
    finish: '체크인 마치기',
    changedTitle: '살펴봐 줘서 고마워요.',
    changedBody: '삶이 바뀌면, 전에 맞던 계획이 지금은 안 맞을 수 있어요 — 아주 자연스러운 일이에요. 체크업이나 주제를 다시 둘러보면, 로드맵이 실제 삶의 속도를 따라가는 데 도움이 될 수 있어요.',
    steadyTitle: '꾸준함이 좋아요.',
    steadyBody: '별일 없다는 것도 하나의 진전이에요. 이런 가벼운 점검이 상태를 신선하게 유지해, 갑작스러운 일에 당황하지 않게 해줘요. 다음 달에 또 만나요.',
    savedNote: '체크인 저장됨',
    seeRoadmap: '내 로드맵 보기',
    revisitCheckup: '체크업 다시 하기',
    backToHub: '허브로 돌아가기',
    lastLabel: '마지막 체크인',
  },
}
