// All Financial Wellness Checkup copy, in English and Korean.
// Plain language, educational only — no product, investment, insurance,
// tax, or legal recommendations anywhere.

export const checkupContent = {
  en: {
    intro: {
      eyebrow: 'Financial Wellness Checkup',
      title: "Let's take an honest look, together.",
      sub: 'Ten plain questions, about two minutes. No sign-up, nothing sent to a server, nothing sold — just a clearer picture of where you stand, and a few small steps to take next.',
      time: '~2 minutes',
      privacy: 'Private — stays on your device',
      start: 'Start checkup',
      resumeTitle: 'You finished a checkup before.',
      resume: 'View your last checkup',
      fresh: 'Start a new one',
      clear: 'Clear it',
    },
    currency: { label: 'Amounts in', usd: '$ USD', krw: '₩ KRW' },
    nav: { back: 'Back', next: 'Next', see: 'See my results', of: 'of', step: 'Question' },
    questions: [
      {
        id: 'income',
        type: 'number',
        label: "What's your rough monthly income?",
        help: 'After tax, a rough estimate is fine — the take-home pay you can actually spend.',
      },
      {
        id: 'essentials',
        type: 'number',
        label: 'About how much goes to essentials each month?',
        help: 'The must-pays: housing, food, utilities, transport, minimum bills.',
      },
      {
        id: 'discretionary',
        type: 'number',
        label: 'And roughly how much on non-essentials?',
        help: 'The nice-to-haves: eating out, subscriptions, fun, extras. Enter 0 if none.',
      },
      {
        id: 'debt',
        type: 'number',
        label: 'How much do you pay toward debts each month?',
        help: 'Credit cards and loans — not counting rent or mortgage. Enter 0 if none.',
      },
      {
        id: 'savings',
        type: 'number',
        label: 'How much could you reach quickly if you needed it?',
        help: 'Cash and savings you could access within a few days. Enter 0 if none.',
      },
      {
        id: 'retirement',
        type: 'choice',
        label: 'Are you putting money toward retirement?',
        help: 'Through work, on your own, anywhere at all.',
        options: [
          { value: 'regularly', label: 'Yes, regularly' },
          { value: 'sometimes', label: 'Now and then' },
          { value: 'notyet', label: 'Not yet' },
          { value: 'notsure', label: "I'm not sure" },
        ],
      },
      {
        id: 'insurance',
        type: 'choice',
        label: 'How clear are you on your insurance coverage?',
        help: 'Health, auto, home or renter, and so on — how well you understand what you have.',
        options: [
          { value: 'notAtAll', label: 'Not clear at all' },
          { value: 'somewhat', label: 'Somewhat clear' },
          { value: 'mostly', label: 'Mostly clear' },
          { value: 'veryClear', label: 'Very clear' },
        ],
      },
      {
        id: 'risk',
        type: 'choice',
        label: 'How do you feel about taking financial risk for possible gain?',
        help: "There's no right answer here — just your honest comfort.",
        options: [
          { value: 0, label: 'Very uncomfortable' },
          { value: 1, label: 'Somewhat uncomfortable' },
          { value: 2, label: 'Neutral' },
          { value: 3, label: 'Somewhat comfortable' },
          { value: 4, label: 'Very comfortable' },
        ],
      },
      {
        id: 'stressWorry',
        type: 'choice',
        label: 'In the past month, how often did money feel stressful?',
        options: [
          { value: 0, label: 'Never' },
          { value: 1, label: 'Rarely' },
          { value: 2, label: 'Sometimes' },
          { value: 3, label: 'Often' },
          { value: 4, label: 'Almost always' },
        ],
      },
      {
        id: 'stressControl',
        type: 'choice',
        label: 'How in control of your finances do you feel?',
        options: [
          { value: 0, label: 'Very in control' },
          { value: 1, label: 'Mostly' },
          { value: 2, label: 'Somewhat' },
          { value: 3, label: 'A little' },
          { value: 4, label: 'Not at all' },
        ],
      },
    ],
    results: {
      eyebrow: 'Your checkup',
      title: "Here's where you stand.",
      sub: 'Read it gently. This is a snapshot of today, not a verdict — and every part comes with one small thing you can do next.',
      whatLabel: 'What this means',
      whyLabel: 'Why it matters',
      stepLabel: 'One small step',
      scoreOutOf: 'out of 100',
      restart: 'Start over',
      home: 'Back to home',
      learn: 'Explore the Learning Center',
      disclaimer:
        "FinE Companion is an educational tool. It doesn't give financial, investment, insurance, tax, or legal advice, and it never recommends products.",
      snapshots: {
        cashflow: {
          title: 'Cash flow',
          perMonth: 'left each month',
          states: {
            short: {
              headline: 'Spending a little more than comes in',
              what: 'Right now your monthly spending edges above your income.',
              why: 'Even a small monthly gap adds up over a year and makes everything else harder to build.',
              step: 'Pick one expense from this month and see whether it could be paused or trimmed.',
            },
            even: {
              headline: 'Just about breaking even',
              what: 'Your income and spending are close to balanced, with a little left over.',
              why: 'Breaking even is a real achievement — and a small surplus is what savings grow from.',
              step: 'Try setting aside one small fixed amount the day you are paid, before anything else.',
            },
            healthy: {
              headline: 'A healthy margin',
              what: 'You keep a comfortable share of your income each month.',
              why: 'That margin is your room to build savings, ease debt, and handle surprises.',
              step: 'Give your leftover a name — a buffer, a goal — so it has somewhere to go.',
            },
            strong: {
              headline: 'A strong margin',
              what: 'You hold on to a strong share of your income each month.',
              why: 'This is the kind of margin that turns goals into milestones over time.',
              step: 'Decide ahead of time where this month’s surplus goes, so it doesn’t drift.',
            },
          },
        },
        emergency: {
          title: 'Emergency fund',
          unit: 'months of must-pays covered',
          states: {
            none: {
              headline: 'Just getting started',
              what: 'You have less than a month of must-pay costs set aside.',
              why: 'A small cash cushion is what keeps a surprise from turning into debt.',
              step: 'Pick one savings spot and put a first small amount in this week.',
            },
            building: {
              headline: 'A cushion forming',
              what: 'You could cover your must-pays for one to three months.',
              why: 'You already have a buffer — many people build toward three to six months as a common guide.',
              step: 'Add a little each month, on the same day, so it grows without thinking.',
            },
            solid: {
              headline: 'Solid footing',
              what: 'You have roughly three to six months of must-pays saved.',
              why: 'This is the range many use as a steady safety net — real breathing room.',
              step: 'Keep it topped up, and let it quietly do its job in the background.',
            },
            cushioned: {
              headline: 'Well cushioned',
              what: 'You have more than six months of must-pays set aside.',
              why: 'You have strong protection against most surprises.',
              step: 'Feel good about this — and consider what your next money goal might be.',
            },
          },
        },
        debt: {
          title: 'Debt pressure',
          ofIncome: 'of income goes to debt',
          states: {
            none: {
              headline: 'No monthly debt pressure',
              what: "You don't have monthly debt payments weighing on your budget.",
              why: 'Staying free of heavy payments keeps more of your income yours.',
              step: 'If you ever borrow, check the monthly payment against your income first.',
            },
            light: {
              headline: 'Light',
              what: 'A small slice of your income goes to debt each month.',
              why: 'A light load is usually very manageable and easy to stay ahead of.',
              step: 'Keep paying on time — that steady record quietly works in your favor.',
            },
            moderate: {
              headline: 'Moderate',
              what: 'A noticeable share of your income goes to debt payments.',
              why: 'It’s workable, but it does limit how much is free for saving and goals.',
              step: 'Try adding a little extra to your smallest debt while covering the rest.',
            },
            heavy: {
              headline: 'Heavy',
              what: 'A large share of your income goes to debt each month.',
              why: 'Many use around a third of income as a comfort line; above it, budgets feel tight.',
              step: 'Pick one debt to focus on first — a single point of progress helps a lot.',
            },
          },
        },
        insurance: {
          title: 'Insurance awareness',
          states: {
            notAtAll: {
              headline: 'Worth a closer look',
              what: 'Your coverage feels unclear to you right now.',
              why: 'Understanding your coverage is how you avoid nasty surprises when you need it.',
              step: 'Find one policy you already have and read what it actually covers.',
            },
            somewhat: {
              headline: 'Partly clear',
              what: 'You have a rough sense of your coverage, with some gaps.',
              why: 'Filling small knowledge gaps now saves confusion at the worst possible time.',
              step: 'Pick the one policy you’re least sure about and skim its summary page.',
            },
            mostly: {
              headline: 'Mostly clear',
              what: 'You understand most of your coverage well.',
              why: 'Clarity here means fewer unknowns and steadier peace of mind.',
              step: 'Do a quick yearly glance to catch anything that has changed.',
            },
            veryClear: {
              headline: 'Clear and confident',
              what: 'You know your coverage well.',
              why: 'That confidence is a quiet, real form of financial security.',
              step: 'Keep a simple list of your policies somewhere easy to find.',
            },
          },
        },
        retirement: {
          title: 'Retirement readiness',
          states: {
            regularly: {
              headline: 'Actively building',
              what: 'You’re putting money toward retirement on a regular basis.',
              why: 'Steady contributions plus time are the biggest allies most people have.',
              step: 'Once a year, check in on what you’re setting aside and how it’s going.',
            },
            sometimes: {
              headline: 'Building now and then',
              what: 'You contribute toward retirement occasionally.',
              why: 'Even irregular saving helps — and a small steady rhythm helps more.',
              step: 'Pick one modest amount you could set aside on a regular schedule.',
            },
            notyet: {
              headline: 'Not started yet',
              what: 'You’re not putting money toward retirement right now.',
              why: 'Starting early gives your money the one thing it loves most: time.',
              step: 'Find out whether your workplace offers any retirement option, and what it is.',
            },
            notsure: {
              headline: 'Worth checking',
              what: 'You’re not certain whether anything is going toward retirement.',
              why: 'Knowing where you stand is the first, freeing step.',
              step: 'Check whether any money currently flows toward retirement for you.',
            },
          },
        },
        stress: {
          title: 'Financial stress (basic)',
          states: {
            low: {
              headline: 'Low',
              what: 'Money hasn’t felt like a heavy weight lately.',
              why: 'Lower stress makes it easier to think clearly and plan ahead.',
              step: 'Notice what’s working for you right now, and keep it.',
            },
            moderate: {
              headline: 'Moderate',
              what: 'Money brings some stress, on and off.',
              why: 'A little stress is normal; naming it keeps it from running the show.',
              step: 'Pick the one money worry that’s loudest and give it ten minutes this week.',
            },
            elevated: {
              headline: 'Elevated',
              what: 'Money has been weighing on you fairly often.',
              why: 'Ongoing stress is real and tiring — and it’s not a personal failing.',
              step: 'Choose one small money task and finish just that. Momentum eases worry.',
            },
            high: {
              headline: 'High',
              what: 'Money stress has been heavy lately.',
              why: 'Carrying this alone is hard, and you don’t have to.',
              step: 'Sharing it with someone you trust, or a free nonprofit financial counselor, can lighten the load.',
            },
          },
        },
        risk: {
          title: 'Risk comfort (basic)',
          note: 'This is about knowing yourself — not a nudge to take more or less risk.',
          states: {
            cautious: {
              headline: 'Cautious',
              what: 'You lean toward safety and steadiness with money.',
              why: 'Knowing this helps you choose paths you can stick with, calmly.',
              step: 'When a money choice feels stressful, trust that steadiness is a valid style.',
            },
            balanced: {
              headline: 'Balanced',
              what: 'You’re somewhere in the middle on financial risk.',
              why: 'A flexible comfort level lets you weigh choices case by case.',
              step: 'Notice which specific decisions feel easy and which feel tense — that’s useful self-knowledge.',
            },
            comfortable: {
              headline: 'Comfortable',
              what: 'You’re relatively at ease with financial risk.',
              why: 'Comfort with uncertainty is fine — pairing it with a safety net keeps it grounded.',
              step: 'Make sure the basics (cushion, must-pays) feel secure alongside any bolder choices.',
            },
          },
        },
      },
      roadmap: {
        eyebrow: 'Your roadmap',
        title: 'A few steps, in your corner.',
        sub: 'Not a to-do list to feel behind on — just a gentle path, from today to the life you’re building.',
        horizons: {
          today: 'Today',
          next30: 'Next 30 days',
          habits: 'Monthly habits',
          sixTwelve: 'Next 6–12 months',
          longterm: 'Long-term vision',
        },
        today: {
          cashflow: 'Jot down your three biggest expenses this month. Just seeing them is a real first step.',
          emergency: 'Pick the place your emergency cushion will live — even an empty account is a start.',
          debt: 'List your debts with their monthly payments, smallest to largest. Clarity first.',
          retirement: 'Write down one question you have about retirement saving. We’ll meet it later.',
          insurance: 'Find one insurance policy you already have and locate what it covers.',
          stress: 'Take one slow breath and name the single money worry that’s loudest. Naming it shrinks it a little.',
          steady: 'Take a moment to notice how far you’ve already come. That counts.',
        },
        next30: {
          cashflow: 'Choose one expense to gently trim, and move what you save somewhere on purpose.',
          emergency: 'Set up one small automatic transfer to savings — even a little, the day you’re paid.',
          debt: 'Put a little extra toward your smallest debt while paying the minimums on the rest.',
          retirement: 'Find out what retirement option, if any, is available to you and how it works.',
          insurance: 'Read one policy fully, so you know what it does and doesn’t cover.',
          stress: 'Pick one money task you’ve been avoiding and do just that one. Momentum eases worry.',
          steady: 'Pick one good habit and make it a little stronger.',
        },
        sixTwelve: {
          cashflow: 'Aim to keep a steady, named margin each month — small and consistent beats big and rare.',
          emergency: 'Build toward one month of must-pay costs, then keep going from there.',
          debt: 'Clear one debt completely, then roll that freed-up payment onto the next.',
          retirement: 'Understand your options well enough to make one confident choice about them.',
          insurance: 'Get clear on each main type of coverage, so none of it is a mystery.',
          stress: 'Build one or two money routines that quietly take worry off your plate.',
          steady: 'Choose one goal that excites you and give it a finish line.',
        },
        habits: [
          'A ten-minute money check-in, same day each week — just you and the numbers, no pressure.',
          'Pay yourself first: move one small set amount to savings the day income arrives.',
          'Before any big purchase, sleep on it a night. Future-you usually says thanks.',
        ],
        longterm: {
          building:
            'The financial life you’re building isn’t about being perfect with money. It’s steady steps that add up to room to breathe, choices that are yours, and a little more calm each season. You’ve started — that’s the hard part.',
          strengthening:
            'You’ve built real footing. From here the work grows quieter: protecting what you’ve made, deepening your cushion, and letting your money serve the life you actually want. Keep going — you’re doing this well.',
        },
      },
    },
  },

  ko: {
    intro: {
      eyebrow: '재정 건강 체크업',
      title: '함께, 솔직하게 한번 살펴봐요.',
      sub: '쉬운 질문 열 개, 약 2분이면 됩니다. 회원가입도, 서버로 보내는 것도, 파는 것도 없습니다 — 그저 지금 당신이 어디에 서 있는지 또렷한 그림과, 다음에 밟을 작은 걸음 몇 개뿐입니다.',
      time: '약 2분',
      privacy: '비공개 — 기기에만 저장됩니다',
      start: '체크업 시작하기',
      resumeTitle: '이전에 마친 체크업이 있어요.',
      resume: '지난 체크업 보기',
      fresh: '새로 시작하기',
      clear: '지우기',
    },
    currency: { label: '금액 단위', usd: '$ 달러', krw: '₩ 원' },
    nav: { back: '이전', next: '다음', see: '결과 보기', of: '중', step: '질문' },
    questions: [
      {
        id: 'income',
        type: 'number',
        label: '한 달 대략적인 수입은 얼마인가요?',
        help: '세후 기준, 대략적인 추정으로 충분합니다 — 실제로 쓸 수 있는 실수령액이요.',
      },
      {
        id: 'essentials',
        type: 'number',
        label: '매달 꼭 필요한 지출은 대략 얼마인가요?',
        help: '반드시 나가는 돈: 주거, 식비, 공과금, 교통, 최소 청구액.',
      },
      {
        id: 'discretionary',
        type: 'number',
        label: '꼭 필요하지 않은 지출은 대략 얼마인가요?',
        help: '있으면 좋은 것들: 외식, 구독, 여가, 여윳돈. 없으면 0을 입력하세요.',
      },
      {
        id: 'debt',
        type: 'number',
        label: '매달 갚는 빚은 얼마인가요?',
        help: '신용카드와 대출 — 월세나 주택담보대출은 제외합니다. 없으면 0을 입력하세요.',
      },
      {
        id: 'savings',
        type: 'number',
        label: '필요할 때 빠르게 꺼낼 수 있는 돈은 얼마인가요?',
        help: '며칠 안에 쓸 수 있는 현금과 예적금. 없으면 0을 입력하세요.',
      },
      {
        id: 'retirement',
        type: 'choice',
        label: '노후를 위해 돈을 모으고 있나요?',
        help: '직장을 통해서든, 개인적으로든, 어디서든요.',
        options: [
          { value: 'regularly', label: '네, 꾸준히요' },
          { value: 'sometimes', label: '가끔씩요' },
          { value: 'notyet', label: '아직이요' },
          { value: 'notsure', label: '잘 모르겠어요' },
        ],
      },
      {
        id: 'insurance',
        type: 'choice',
        label: '내 보험 보장 내용을 얼마나 알고 있나요?',
        help: '건강, 자동차, 주택·임차 등 — 내가 가진 보장을 얼마나 이해하는지요.',
        options: [
          { value: 'notAtAll', label: '전혀 모르겠어요' },
          { value: 'somewhat', label: '조금 알아요' },
          { value: 'mostly', label: '대체로 알아요' },
          { value: 'veryClear', label: '아주 잘 알아요' },
        ],
      },
      {
        id: 'risk',
        type: 'choice',
        label: '이익을 위해 재정적 위험을 감수하는 것에 대해 어떻게 느끼나요?',
        help: '정답은 없어요 — 그저 솔직한 편안함의 정도면 됩니다.',
        options: [
          { value: 0, label: '매우 불편해요' },
          { value: 1, label: '조금 불편해요' },
          { value: 2, label: '보통이에요' },
          { value: 3, label: '조금 편해요' },
          { value: 4, label: '매우 편해요' },
        ],
      },
      {
        id: 'stressWorry',
        type: 'choice',
        label: '지난 한 달 동안 돈 때문에 스트레스를 느낀 적이 얼마나 되나요?',
        options: [
          { value: 0, label: '전혀 없어요' },
          { value: 1, label: '드물게요' },
          { value: 2, label: '가끔요' },
          { value: 3, label: '자주요' },
          { value: 4, label: '거의 항상요' },
        ],
      },
      {
        id: 'stressControl',
        type: 'choice',
        label: '내 재정을 얼마나 잘 통제하고 있다고 느끼나요?',
        options: [
          { value: 0, label: '아주 잘 통제해요' },
          { value: 1, label: '대체로요' },
          { value: 2, label: '어느 정도요' },
          { value: 3, label: '조금요' },
          { value: 4, label: '전혀요' },
        ],
      },
    ],
    results: {
      eyebrow: '나의 체크업',
      title: '지금 당신은 여기에 있어요.',
      sub: '편안하게 읽어 주세요. 이것은 오늘의 스냅샷이지 평가가 아닙니다 — 그리고 모든 항목에는 다음에 할 수 있는 작은 한 가지가 담겨 있어요.',
      whatLabel: '무슨 뜻인가요',
      whyLabel: '왜 중요한가요',
      stepLabel: '작은 한 걸음',
      scoreOutOf: '100점 만점',
      restart: '다시 시작',
      home: '홈으로',
      learn: '러닝 센터 둘러보기',
      disclaimer:
        'FinE Companion은 교육 도구입니다. 금융·투자·보험·세무·법률 자문을 제공하지 않으며, 어떤 상품도 추천하지 않습니다.',
      snapshots: {
        cashflow: {
          title: '현금 흐름',
          perMonth: '매달 남는 돈',
          states: {
            short: {
              headline: '들어오는 것보다 조금 더 쓰고 있어요',
              what: '지금은 한 달 지출이 수입을 살짝 넘고 있어요.',
              why: '작은 차이도 1년이면 쌓여, 다른 모든 것을 쌓기 어렵게 만들어요.',
              step: '이번 달 지출 하나를 골라, 잠시 멈추거나 줄일 수 있는지 살펴보세요.',
            },
            even: {
              headline: '거의 수지가 맞아요',
              what: '수입과 지출이 균형에 가깝고, 조금 남아요.',
              why: '수지를 맞추는 건 진짜 성취예요 — 그리고 작은 여유가 저축의 씨앗이 됩니다.',
              step: '월급 받는 날, 무엇보다 먼저 작은 고정 금액을 따로 떼어 보세요.',
            },
            healthy: {
              headline: '건강한 여유',
              what: '매달 수입의 넉넉한 몫을 남기고 있어요.',
              why: '그 여유가 저축을 쌓고, 빚을 덜고, 예상 밖 일을 감당할 공간이 됩니다.',
              step: '남는 돈에 이름을 붙여 주세요 — 비상금, 목표 — 갈 곳이 생기도록요.',
            },
            strong: {
              headline: '든든한 여유',
              what: '매달 수입의 큰 몫을 지켜 내고 있어요.',
              why: '이런 여유가 시간이 지나며 목표를 이정표로 바꿔 줍니다.',
              step: '이번 달 남는 돈이 갈 곳을 미리 정해, 흩어지지 않게 하세요.',
            },
          },
        },
        emergency: {
          title: '비상금',
          unit: '개월치 필수 지출 감당 가능',
          states: {
            none: {
              headline: '이제 막 시작',
              what: '필수 지출 한 달치도 채 모아 두지 못한 상태예요.',
              why: '작은 현금 완충이 예상 밖의 일을 빚으로 바꾸지 않게 막아 줍니다.',
              step: '저축할 곳 하나를 정하고, 이번 주에 첫 작은 금액을 넣어 보세요.',
            },
            building: {
              headline: '완충이 만들어지는 중',
              what: '필수 지출을 한 달에서 석 달 정도 감당할 수 있어요.',
              why: '이미 완충이 있어요 — 흔히 3~6개월을 하나의 기준으로 삼습니다.',
              step: '매달 같은 날 조금씩 더해, 신경 쓰지 않아도 자라게 하세요.',
            },
            solid: {
              headline: '단단한 발판',
              what: '대략 3~6개월치 필수 지출을 모아 두었어요.',
              why: '많은 사람이 안정적인 안전망으로 삼는 범위예요 — 진짜 숨 쉴 공간이죠.',
              step: '조금씩 채워 두고, 뒤에서 조용히 제 역할을 하게 두세요.',
            },
            cushioned: {
              headline: '넉넉한 완충',
              what: '6개월치 이상의 필수 지출을 모아 두었어요.',
              why: '웬만한 예상 밖의 일에 든든한 보호막이 있어요.',
              step: '스스로를 칭찬해 주세요 — 그리고 다음 돈 목표가 무엇일지 그려 보세요.',
            },
          },
        },
        debt: {
          title: '부채 부담',
          ofIncome: '수입 중 빚으로',
          states: {
            none: {
              headline: '매달 갚는 빚 부담 없음',
              what: '예산을 누르는 월별 빚 상환이 없어요.',
              why: '무거운 상환에서 자유로울수록 수입의 더 많은 부분이 온전히 내 것이 됩니다.',
              step: '혹시 빌리게 된다면, 월 상환액을 수입과 먼저 비교해 보세요.',
            },
            light: {
              headline: '가벼움',
              what: '수입의 작은 몫이 매달 빚으로 나가요.',
              why: '가벼운 부담은 대체로 감당하기 쉽고 앞서 나가기도 좋아요.',
              step: '제때 갚아 나가세요 — 그 꾸준한 기록이 조용히 당신 편이 됩니다.',
            },
            moderate: {
              headline: '보통',
              what: '수입의 눈에 띄는 몫이 빚 상환으로 나가요.',
              why: '감당은 되지만, 저축과 목표에 쓸 여유는 줄어들어요.',
              step: '나머지를 갚으면서, 가장 작은 빚에 조금씩 더 얹어 보세요.',
            },
            heavy: {
              headline: '무거움',
              what: '수입의 큰 몫이 매달 빚으로 나가요.',
              why: '흔히 수입의 3분의 1쯤을 기준선으로 보는데, 그 위로는 예산이 빠듯해집니다.',
              step: '먼저 집중할 빚 하나를 정하세요 — 한 곳의 진전이 큰 힘이 됩니다.',
            },
          },
        },
        insurance: {
          title: '보험 이해도',
          states: {
            notAtAll: {
              headline: '좀 더 살펴볼 필요',
              what: '지금은 내 보장 내용이 잘 와닿지 않는 상태예요.',
              why: '보장을 이해해 두는 것이, 정작 필요할 때의 낭패를 막는 길입니다.',
              step: '이미 가진 보험 하나를 찾아, 무엇을 보장하는지 읽어 보세요.',
            },
            somewhat: {
              headline: '조금 알고 있음',
              what: '보장 내용을 대략 알지만, 빈틈이 좀 있어요.',
              why: '지금 작은 빈틈을 메워 두면, 가장 곤란한 순간의 혼란을 줄일 수 있어요.',
              step: '가장 불확실한 보험 하나를 골라 요약 페이지를 훑어보세요.',
            },
            mostly: {
              headline: '대체로 알고 있음',
              what: '보장 내용을 대부분 잘 이해하고 있어요.',
              why: '여기서의 또렷함은 불확실함을 줄이고 마음을 더 놓이게 해요.',
              step: '해마다 한 번 빠르게 훑어, 달라진 점이 있는지 확인하세요.',
            },
            veryClear: {
              headline: '또렷하고 자신 있음',
              what: '내 보장 내용을 잘 알고 있어요.',
              why: '그 자신감은 조용하지만 진짜인 재정적 안정의 한 형태예요.',
              step: '내 보험 목록을 찾기 쉬운 곳에 간단히 적어 두세요.',
            },
          },
        },
        retirement: {
          title: '노후 준비',
          states: {
            regularly: {
              headline: '적극적으로 쌓는 중',
              what: '노후를 위해 꾸준히 돈을 넣고 있어요.',
              why: '꾸준한 적립과 시간은 대부분의 사람에게 가장 든든한 아군입니다.',
              step: '해마다 한 번, 얼마를 넣고 있고 어떻게 되어 가는지 점검하세요.',
            },
            sometimes: {
              headline: '가끔씩 쌓는 중',
              what: '노후를 위해 이따금 돈을 넣고 있어요.',
              why: '불규칙한 저축도 도움이 돼요 — 작더라도 꾸준한 리듬이면 더 좋고요.',
              step: '정기적으로 떼어 둘 수 있는 적당한 금액 하나를 정해 보세요.',
            },
            notyet: {
              headline: '아직 시작 전',
              what: '지금은 노후를 위해 돈을 넣고 있지 않아요.',
              why: '일찍 시작하면, 돈이 가장 좋아하는 한 가지 — 시간 — 을 얻습니다.',
              step: '직장에 노후 관련 제도가 있는지, 있다면 무엇인지 알아보세요.',
            },
            notsure: {
              headline: '확인이 필요',
              what: '노후로 무언가 들어가고 있는지 확실치 않은 상태예요.',
              why: '어디에 서 있는지 아는 것이, 홀가분한 첫걸음이에요.',
              step: '지금 노후를 위해 흘러가는 돈이 있는지 확인해 보세요.',
            },
          },
        },
        stress: {
          title: '재정 스트레스 (기본)',
          states: {
            low: {
              headline: '낮음',
              what: '요즘 돈이 큰 짐처럼 느껴지지는 않았어요.',
              why: '스트레스가 낮으면 더 또렷하게 생각하고 앞을 내다보기 쉬워요.',
              step: '지금 나에게 잘 맞는 것이 무엇인지 살펴, 그대로 이어가세요.',
            },
            moderate: {
              headline: '보통',
              what: '돈이 이따금 스트레스를 주고 있어요.',
              why: '약간의 스트레스는 자연스러워요; 이름을 붙이면 휘둘리지 않게 됩니다.',
              step: '가장 큰 돈 걱정 하나를 골라, 이번 주에 10분만 들여 보세요.',
            },
            elevated: {
              headline: '다소 높음',
              what: '돈이 꽤 자주 마음을 눌러 왔어요.',
              why: '이어지는 스트레스는 실제로 힘든 일이고, 당신의 잘못이 아니에요.',
              step: '작은 돈 관련 일 하나를 골라 그것만 끝내 보세요. 흐름이 걱정을 덜어 줍니다.',
            },
            high: {
              headline: '높음',
              what: '요즘 돈 스트레스가 무거웠어요.',
              why: '이걸 혼자 지는 건 힘든 일이에요. 혼자 하지 않아도 됩니다.',
              step: '믿는 사람이나 무료 비영리 재정 상담과 나누면, 짐이 한결 가벼워질 수 있어요.',
            },
          },
        },
        risk: {
          title: '위험 감수 성향 (기본)',
          note: '이건 스스로를 아는 것에 대한 이야기예요 — 위험을 더 지라거나 덜 지라는 권유가 아닙니다.',
          states: {
            cautious: {
              headline: '신중한 편',
              what: '돈에 관해 안전과 안정 쪽으로 기울어 있어요.',
              why: '이를 알면, 차분하게 지켜 나갈 수 있는 길을 고를 수 있어요.',
              step: '돈 선택이 부담스러울 때, 신중함도 하나의 온전한 방식임을 믿어 주세요.',
            },
            balanced: {
              headline: '균형 잡힌 편',
              what: '재정적 위험에 대해 중간 어딘가에 있어요.',
              why: '유연한 편안함의 정도는, 사안마다 저울질할 여지를 줍니다.',
              step: '어떤 결정이 편하고 어떤 결정이 긴장되는지 살펴보세요 — 유용한 자기 이해예요.',
            },
            comfortable: {
              headline: '편안한 편',
              what: '재정적 위험에 비교적 편안한 편이에요.',
              why: '불확실함에 편안한 건 괜찮아요 — 안전망과 함께라면 더 단단해집니다.',
              step: '과감한 선택 곁에, 기본(완충·필수 지출)이 든든한지 꼭 확인하세요.',
            },
          },
        },
      },
      roadmap: {
        eyebrow: '나의 로드맵',
        title: '당신 편에 선 몇 걸음.',
        sub: '뒤처진 기분이 드는 할 일 목록이 아니라 — 오늘부터 당신이 만들어 가는 삶까지, 부드러운 길이에요.',
        horizons: {
          today: '오늘',
          next30: '앞으로 30일',
          habits: '매달의 습관',
          sixTwelve: '앞으로 6~12개월',
          longterm: '장기적인 그림',
        },
        today: {
          cashflow: '이번 달 가장 큰 지출 세 가지를 적어 보세요. 눈으로 보는 것만으로도 진짜 첫걸음이에요.',
          emergency: '비상금이 머물 곳을 정하세요 — 빈 계좌라도 시작이에요.',
          debt: '빚을 월 상환액과 함께 작은 것부터 큰 것 순으로 적어 보세요. 또렷함이 먼저예요.',
          retirement: '노후 저축에 대해 궁금한 점 하나를 적어 두세요. 나중에 함께 풀어 봐요.',
          insurance: '이미 가진 보험 하나를 찾아, 무엇을 보장하는지 짚어 보세요.',
          stress: '천천히 숨 한 번 쉬고, 가장 큰 돈 걱정 하나에 이름을 붙여 보세요. 이름을 붙이면 조금 작아져요.',
          steady: '지금까지 얼마나 왔는지 잠시 돌아보세요. 그것도 성취예요.',
        },
        next30: {
          cashflow: '줄일 지출 하나를 정하고, 아낀 돈을 의도적으로 어딘가로 옮겨 보세요.',
          emergency: '작은 자동이체 하나를 걸어 두세요 — 월급 받는 날, 조금씩이라도요.',
          debt: '나머지는 최소 금액으로 갚으면서, 가장 작은 빚에 조금 더 얹어 보세요.',
          retirement: '나에게 어떤 노후 제도가 있는지, 어떻게 작동하는지 알아보세요.',
          insurance: '보험 하나를 처음부터 끝까지 읽어, 무엇이 되고 안 되는지 알아 두세요.',
          stress: '미뤄 온 돈 관련 일 하나만 해보세요. 흐름이 걱정을 덜어 줍니다.',
          steady: '좋은 습관 하나를 골라 조금 더 단단하게 만들어 보세요.',
        },
        sixTwelve: {
          cashflow: '매달 이름 붙인 여유를 꾸준히 지키는 걸 목표로 하세요 — 크고 드문 것보다 작고 꾸준한 게 이겨요.',
          emergency: '먼저 한 달치 필수 지출을 목표로 쌓고, 거기서 계속 이어가세요.',
          debt: '빚 하나를 완전히 갚고, 그 여윳돈을 다음 빚으로 굴려 보세요.',
          retirement: '자신 있게 하나를 선택할 수 있을 만큼 제도를 이해해 두세요.',
          insurance: '주요 보장 종류마다 또렷해져, 어느 것도 미스터리로 남지 않게 하세요.',
          stress: '걱정을 조용히 덜어 줄 돈 루틴 한두 가지를 만들어 보세요.',
          steady: '설레는 목표 하나를 골라, 결승선을 그어 주세요.',
        },
        habits: [
          '매주 같은 날, 10분 돈 점검 — 그저 나와 숫자만, 부담 없이요.',
          '나에게 먼저 주기: 수입이 들어오는 날 작은 고정 금액을 저축으로 옮기세요.',
          '큰 지출 전엔 하룻밤 자고 결정하세요. 미래의 내가 대개 고마워합니다.',
        ],
        longterm: {
          building:
            '당신이 만들어 가는 재정 생활은 돈을 완벽하게 다루는 일이 아니에요. 숨 쉴 공간, 온전히 내 것인 선택, 그리고 계절마다 조금씩 더 큰 평온으로 이어지는 꾸준한 걸음이죠. 당신은 이미 시작했어요 — 그게 가장 어려운 부분입니다.',
          strengthening:
            '이미 단단한 발판을 만들었어요. 여기서부터는 일이 더 조용해집니다: 이룬 것을 지키고, 완충을 두텁게 하고, 돈이 당신이 진짜 원하는 삶을 돕게 하는 거죠. 계속 가세요 — 아주 잘하고 있어요.',
        },
      },
    },
  },
}
