// Companion Hub content. A place to explore, not a funnel into a survey.
export const hubContent = {
  en: {
    eyebrow: 'Your companion',
    title: 'A calmer way to understand your money.',
    sub: 'No long survey to finish. Just short, honest topics you can explore in a few minutes each — and a roadmap that quietly grows as you do.',
    trust: 'Always on your side. We never sell anything, and nothing you do here ever leaves your device.',
    promiseShort: 'Always on your side — never selling, and nothing you do here leaves your device.',
    door: {
      kicker: 'New here?',
      line: 'If you’re not sure where to begin, take a short, honest look at where you stand today — about two minutes, and it stays on your device.',
      cta: 'Start with a short look',
    },
    assure: ['About 2 minutes to start', 'No wrong answers', 'Stays on your device', 'Educational, not advice'],
    hero: {
      welcome: 'Welcome',
      headline: 'Money is part of your life. Let’s understand it, together.',
      body: 'You don’t have to be “good with money,” and you don’t have to solve everything today. We’ll go gently — one small step at a time — and you can always come back. Begin wherever feels right.',
      begin: 'Start with a gentle look',
      safeNote: 'About two minutes · nothing to sign up for · stays on your device',
    },
    concerns: {
      question: 'What would you like help with today?',
      lead: 'Choose whatever feels closest to how things are right now. There’s no wrong answer, and whatever you don’t pick will still be here when you come back.',
      hint: 'Open whichever feels most like you',
      doors: [
        {
          feeling: 'Right now, money feels tight or heavy.',
          reply: 'Let’s start by simply seeing where things stand — gently, and without any judgment.',
          ids: ['cashflow', 'stress', 'risk'],
        },
        {
          feeling: 'I want to take care of the people I love.',
          reply: 'A few small things can keep the people who depend on you steady, whatever comes.',
          ids: ['insurance', 'estate', 'education'],
        },
        {
          feeling: 'I’m ready to look a little further ahead.',
          reply: 'Small, early steps have a quiet way of adding up to the life you’re hoping for.',
          ids: ['retirement', 'investing', 'tax'],
        },
      ],
      unsure: {
        feeling: 'Honestly, I’m not sure where to start.',
        reply: 'That’s completely okay — most people feel that way. We can begin with one short, honest look at where you are today.',
        cta: 'Start with a gentle look',
      },
    },
    startHereLabel: 'Start here',
    todaysLessonLabel: "Today's lesson",
    todaysTipLabel: "Today's companion tip",
    nextStepLabel: 'Recommended next step',
    exploreLabel: 'What would you like help with today?',
    toolsLabel: 'Your companion',
    minutesLabel: 'min',
    exploreCta: 'Explore',
    exploredBadge: 'Explored',
    startCta: 'Start',
    companionLabel: 'For you today',
    exploreIntro: 'Pick whatever feels closest to what’s on your mind. Each one takes just a few minutes.',
    strip: {
      ongoing: 'A companion for the long run — come back whenever life shifts.',
      horizonsMini: ['Today', 'Next 30 days', 'Monthly', '6–12 months', 'Long-term'],
      nowLabel: 'You are here',
      checkinNudge: 'New month? Take a one-minute check-in',
    },
    learningTeaser: {
      label: 'A quick read',
      title: 'Teach me something useful in two minutes.',
      body: 'A calm place for the thinking under every topic — why we behave the way we do with money.',
      cta: 'Show me something',
    },
    shelves: [
      { label: 'When money’s been on your mind', intro: 'The everyday stuff — where it goes, how it feels, and finding your footing.', ids: ['cashflow', 'stress', 'risk'] },
      { label: 'When you want to feel protected', intro: 'Making sure a hard surprise stays a surprise, not a disaster.', ids: ['insurance', 'estate'] },
      { label: 'When you’re thinking ahead', intro: 'Small steps today toward the life you’re building.', ids: ['retirement', 'education', 'investing', 'tax'] },
    ],
    labels: {
      availableNow: 'Available now',
      comingSoon: 'Coming soon',
      tryFirst: 'Try this first',
      goodNext: 'Good next step',
      twoMin: '2-minute topic',
      quick: '1-minute check-in',
    },
    journey: {
      label: 'Your journey so far',
      exploredOf: 'topics explored',
      roadmapEmpty: 'Your roadmap begins the moment you explore a topic or check in.',
      roadmapGrowing: 'Your roadmap is growing',
      checkupPending: 'Checkup not taken yet',
      checkupDone: 'Checkup done',
      seeRoadmap: 'Open your roadmap',
      comeBack: 'A monthly check-in keeps it close to your real life.',
    },
    checkin: {
      title: 'Monthly Check-in',
      tagline: 'A one-minute pause to notice what\u2019s changed in your life.',
      cta: 'Check in',
      comeBackNote: 'Come back next month',
    },
    comingSoon: [
      { title: 'Goals & Values', tagline: 'Connect your money to what actually matters to you.' },
      { title: 'Life Changes', tagline: 'Gentle guidance for the big moments — a move, a job, a family shift.' },
    ],
    lessons: [
      { title: 'Cash flow is a story, not a scoreboard.', body: 'Every plan begins by simply seeing where money flows — to find your strengths first, and the one or two gaps worth working on.' },
      { title: 'Time usually beats timing.', body: 'In retirement saving, how long your money grows matters more than how clever you are. Starting small early tends to win.' },
      { title: 'Insure the catastrophe, not the inconvenience.', body: 'Coverage is really for the losses you couldn\u2019t absorb yourself — and what those are quietly changes as life changes.' },
      { title: 'A refund isn\u2019t a reward.', body: 'A big tax refund is often just your own money returned to you late. Steady awareness beats a spring surprise.' },
      { title: 'You can borrow for college — not for retirement.', body: 'Loving parents often fund education first, but a stable foundation usually comes first. Sequence matters.' },
      { title: 'Naming a worry shrinks it.', body: 'Money stress tracks uncertainty, not virtue. It eases with clarity and small steps, not self-blame.' },
    ],
    tips: [
      'Notice one expense today — just notice it, no judgment. Awareness is where every plan starts.',
      'Move a tiny amount to savings the day you\u2019re paid, before anything else. Saving before spending is what makes it happen.',
      'Read what one of your insurance policies actually covers. Understanding beats buying.',
      'Ask what retirement option, if any, you already have. Knowing is the first step.',
      'Sleep one night on any big purchase. Future-you usually says thanks.',
      'Say your loudest money worry out loud, once. Named, it gets a little smaller.',
    ],
    next: {
      checkup: { title: 'Help me understand where I am today.', body: 'A gentle two-minute checkup gives your roadmap a starting point — no pressure, and nothing saved off your device.', cta: 'Try the checkup', meta: '2 min · See where your money is going' },
      explore: { title: 'Explore something new', body: 'You\u2019ve got momentum. Here\u2019s a topic you haven\u2019t opened yet, ready in a few minutes.', cta: 'Explore', meta: '2 min · Understand one new topic' },
      learning: { title: 'Deepen what you know', body: 'You\u2019ve explored a lot. The Learning Center gathers the ideas behind it all in one calm place.', cta: 'Open the Learning Center', meta: '5 min · The ideas behind it all' },
    },
    cards: {
      checkup: { title: 'Where you are today', tagline: 'A gentle two-minute snapshot of where you stand — your path starts here.', minutes: 2 },
      learning: { title: 'Learning Center', tagline: 'Behavioral insights, common mistakes, and the ideas behind it all.' },
      roadmap: { title: 'Your Roadmap', tagline: 'Everything you explore gathers here into a path that\u2019s yours.' },
    },
  },
  ko: {
    eyebrow: '당신의 동반자',
    title: '내 돈을 이해하는, 더 차분한 방법.',
    sub: '끝내야 할 긴 설문은 없어요. 각각 몇 분이면 되는 짧고 정직한 주제들을 탐색하면 — 당신과 함께 조용히 자라는 로드맵이 생겨요.',
    trust: '언제나 당신 편이에요. 무엇도 팔지 않고, 여기서 하는 어떤 것도 기기를 떠나지 않아요.',
    promiseShort: '언제나 당신 편 — 무엇도 팔지 않고, 여기서 하는 어떤 것도 기기를 떠나지 않아요.',
    door: {
      kicker: '처음이신가요?',
      line: '어디서 시작할지 모르겠다면, 지금 서 있는 자리를 짧고 정직하게 살펴보세요 — 약 2분이면 되고, 기기에만 남아요.',
      cta: '짧게 살펴보기',
    },
    assure: ['시작까지 약 2분', '틀린 답은 없어요', '기기에만 저장돼요', '교육 목적, 자문 아님'],
    hero: {
      welcome: '환영합니다',
      headline: '돈은 삶의 일부예요. 함께, 천천히 이해해 봐요.',
      body: '돈을 잘 알아야 시작할 수 있는 건 아니에요. 오늘 모든 걸 해결하지 않아도 괜찮아요. 작은 한 걸음씩, 천천히 — 언제든 다시 와도 돼요. 마음이 가는 곳에서 시작하세요.',
      begin: '가볍게 살펴보기',
      safeNote: '약 2분 · 가입 필요 없음 · 기기에만 저장돼요',
    },
    concerns: {
      question: '오늘 무엇을 도와드릴까요?',
      lead: '지금 상황에 가장 가까운 걸 골라 보세요. 틀린 답은 없고, 지금 고르지 않은 것들도 다시 오면 그대로 있을 거예요.',
      hint: '가장 나 같은 걸 열어 보세요',
      doors: [
        {
          feeling: '요즘 돈이 빠듯하거나 무겁게 느껴져요.',
          reply: '판단 없이, 지금 어디에 서 있는지 부드럽게 살펴보는 것부터 시작해요.',
          ids: ['cashflow', 'stress', 'risk'],
        },
        {
          feeling: '사랑하는 사람들을 잘 지키고 싶어요.',
          reply: '작은 몇 가지가, 나에게 기대는 사람들을 어떤 일이 와도 든든하게 지켜 줄 수 있어요.',
          ids: ['insurance', 'estate', 'education'],
        },
        {
          feeling: '이제 조금 더 앞을 내다볼 준비가 됐어요.',
          reply: '이르고 작은 걸음들이, 바라는 삶으로 조용히 쌓여 가요.',
          ids: ['retirement', 'investing', 'tax'],
        },
      ],
      unsure: {
        feeling: '솔직히 어디서 시작할지 모르겠어요.',
        reply: '괜찮아요 — 대부분 그렇게 느껴요. 지금 어디 있는지 짧고 정직하게 한 번 살펴보는 것부터 시작할 수 있어요.',
        cta: '가볍게 살펴보기',
      },
    },
    startHereLabel: '여기서 시작',
    todaysLessonLabel: '오늘의 배움',
    todaysTipLabel: '오늘의 컴패니언 팁',
    nextStepLabel: '추천 다음 단계',
    exploreLabel: '오늘 무엇을 도와드릴까요?',
    toolsLabel: '나의 동반자',
    minutesLabel: '분',
    exploreCta: '탐색',
    exploredBadge: '탐색함',
    startCta: '시작',
    companionLabel: '오늘 당신에게',
    exploreIntro: '지금 마음에 가장 가까운 걸 골라 보세요. 각각 몇 분이면 돼요.',
    strip: {
      ongoing: '오래 함께하는 동반자 — 삶이 바뀔 때 언제든 다시 오세요.',
      horizonsMini: ['오늘', '앞으로 30일', '매달', '6–12개월', '장기'],
      nowLabel: '지금 여기',
      checkinNudge: '새 달인가요? 1분 체크인을 해보세요',
    },
    learningTeaser: {
      label: '잠깐 읽기',
      title: '2분이면 되는, 알아 두면 좋은 것.',
      body: '모든 주제 아래 흐르는 생각을 위한 차분한 공간 — 우리가 돈 앞에서 왜 그렇게 행동하는지.',
      cta: '보여 주세요',
    },
    shelves: [
      { label: '요즘 돈이 마음에 걸린다면', intro: '어디로 가는지, 어떤 기분인지, 발판을 찾는 일 — 일상의 돈 이야기예요.', ids: ['cashflow', 'stress', 'risk'] },
      { label: '든든하게 보호받고 싶다면', intro: '힘든 일이 재앙이 아니라 그저 놀랄 일로 남도록.', ids: ['insurance', 'estate'] },
      { label: '앞날을 생각한다면', intro: '만들어 가는 삶을 향한 오늘의 작은 걸음들.', ids: ['retirement', 'education', 'investing', 'tax'] },
    ],
    labels: {
      availableNow: '지금 이용 가능',
      comingSoon: '곧 공개',
      tryFirst: '먼저 해보기',
      goodNext: '좋은 다음 단계',
      twoMin: '2분 주제',
      quick: '1분 체크인',
    },
    journey: {
      label: '지금까지의 여정',
      exploredOf: '주제 탐색함',
      roadmapEmpty: '주제를 탐색하거나 체크인하는 순간 로드맵이 시작돼요.',
      roadmapGrowing: '로드맵이 자라고 있어요',
      checkupPending: '체크업 아직 안 함',
      checkupDone: '체크업 완료',
      seeRoadmap: '로드맵 열기',
      comeBack: '월간 체크인이 로드맵을 실제 삶에 가깝게 유지해 줘요.',
    },
    checkin: {
      title: '월간 체크인',
      tagline: '삶에서 무엇이 달라졌는지 살펴보는 1분의 멈춤.',
      cta: '체크인하기',
      comeBackNote: '다음 달에 다시 오세요',
    },
    comingSoon: [
      { title: '목표와 가치', tagline: '돈을 정말 소중한 것과 연결해요.' },
      { title: '삶의 변화', tagline: '이사, 이직, 가족의 변화 같은 큰 순간을 위한 부드러운 안내.' },
    ],
    lessons: [
      { title: '현금 흐름은 점수판이 아니라 이야기예요.', body: '모든 계획은 그저 돈이 어디로 흐르는지 보는 데서 시작해요 — 먼저 강점을, 그리고 손볼 만한 한두 빈틈을 찾으려고요.' },
      { title: '대개 타이밍보다 시간이 이겨요.', body: '은퇴 저축에선, 얼마나 영리한가보다 돈이 얼마나 오래 자라는가가 더 중요해요. 일찍 작게 시작하는 쪽이 이기곤 하죠.' },
      { title: '불편이 아니라 재앙에 대비하세요.', body: '보험은 스스로 감당 못 할 손실을 위한 것 — 그 목록은 삶이 변하면 조용히 함께 변해요.' },
      { title: '환급은 상이 아니에요.', body: '큰 세금 환급은 대개 내 돈을 늦게 돌려받는 것뿐이에요. 봄의 깜짝 선물보다 연중 꾸준한 감각이 나아요.' },
      { title: '학자금은 빌릴 수 있어도, 은퇴는 빌릴 수 없어요.', body: '사랑하는 부모는 흔히 교육을 먼저 챙기지만, 대개 튼튼한 토대가 먼저예요. 순서가 중요해요.' },
      { title: '걱정에 이름을 붙이면 작아져요.', body: '돈 스트레스는 미덕이 아니라 불확실성을 따라와요. 자책이 아니라 또렷함과 작은 걸음으로 누그러집니다.' },
    ],
    tips: [
      '오늘 지출 하나를 살펴보세요 — 판단 없이, 그저 보기만요. 알아차림이 모든 계획의 시작이에요.',
      '월급 받는 날, 무엇보다 먼저 작은 금액을 저축으로 옮기세요. 쓰기 전에 저축해야 이뤄져요.',
      '가진 보험 하나가 실제로 무엇을 보장하는지 읽어 보세요. 이해가 가입을 이겨요.',
      '나에게 어떤 은퇴 제도가 있는지 알아보세요. 아는 것이 첫걸음이에요.',
      '큰 지출은 하룻밤 자고 결정하세요. 미래의 내가 대개 고마워해요.',
      '가장 큰 돈 걱정을 한 번 소리 내어 말해 보세요. 이름이 붙으면 조금 작아져요.',
    ],
    next: {
      checkup: { title: '지금 내가 어디 있는지 알고 싶어요.', body: '부드러운 2분 체크업이 로드맵의 출발점을 만들어 줘요 — 부담 없이, 기기를 벗어나 저장되는 것도 없이요.', cta: '체크업 해보기', meta: '2분 · 내 돈이 어디로 가는지 보기' },
      explore: { title: '새로운 것을 탐색해요', body: '흐름을 타고 있네요. 아직 열지 않은 주제가 여기 있어요, 몇 분이면 돼요.', cta: '탐색하기', meta: '2분 · 한 가지 주제 이해하기' },
      learning: { title: '아는 것을 더 깊게', body: '많이 탐색했어요. 러닝 센터가 그 뒤의 생각들을 한 곳에 차분히 모아 둡니다.', cta: '러닝 센터 열기', meta: '5분 · 그 뒤에 있는 생각들' },
    },
    cards: {
      checkup: { title: '지금 나의 자리', tagline: '지금 어디에 서 있는지 부드러운 2분 스냅샷 — 나의 길이 여기서 시작돼요.', minutes: 2 },
      learning: { title: '러닝 센터', tagline: '행동 인사이트, 흔한 실수, 그리고 그 뒤의 생각들.' },
      roadmap: { title: '나의 로드맵', tagline: '탐색한 모든 것이 나만의 길로 이곳에 모여요.' },
    },
  },
}
