// Companion Hub content. A place to explore, not a funnel into a survey.
export const hubContent = {
  en: {
    eyebrow: 'The Companion Hub',
    title: 'A calmer way to understand your money.',
    sub: 'No long survey to finish. Just short, honest topics you can explore in a few minutes each — and a roadmap that quietly grows as you do.',
    trust: 'Educational, always. We never sell products, and nothing leaves your device.',
    todaysLessonLabel: "Today's lesson",
    todaysTipLabel: "Today's companion tip",
    nextStepLabel: 'Recommended next step',
    exploreLabel: 'Explore a topic',
    toolsLabel: 'Your companion',
    minutesLabel: 'min',
    exploreCta: 'Explore',
    exploredBadge: 'Explored',
    startCta: 'Start',
    lessons: [
      { title: 'Cash flow is a story, not a scoreboard.', body: 'Every plan begins by simply seeing where money flows — to find your strengths first, and the one or two gaps worth working on.' },
      { title: 'Time usually beats timing.', body: 'In retirement saving, how long your money grows matters more than how clever you are. Starting small early tends to win.' },
      { title: 'Insure the catastrophe, not the inconvenience.', body: 'Coverage is really for the losses you couldn\u2019t absorb yourself — and what those are quietly changes as life changes.' },
      { title: 'A refund isn\u2019t a reward.', body: 'A big tax refund is often just your own money returned to you late. Steady awareness beats a spring surprise.' },
      { title: 'You can borrow for college — not for retirement.', body: 'Loving parents often fund education first, but a stable foundation usually comes first. Sequence matters.' },
      { title: 'Naming a worry shrinks it.', body: 'Money stress tracks uncertainty, not virtue. It eases with clarity and small steps, not self-blame.' },
    ],
    tips: [
      'Notice one expense today — just notice it, no judgment. Awareness is where every plan starts.',
      'Move a tiny amount to savings the day you\u2019re paid, before anything else. Saving before spending is what makes it happen.',
      'Read what one of your insurance policies actually covers. Understanding beats buying.',
      'Ask what retirement option, if any, you already have. Knowing is the first step.',
      'Sleep one night on any big purchase. Future-you usually says thanks.',
      'Say your loudest money worry out loud, once. Named, it gets a little smaller.',
    ],
    next: {
      checkup: { title: 'Get your bearings first', body: 'A gentle two-minute checkup gives your roadmap a starting point — no pressure, and nothing saved off your device.', cta: 'Try the checkup' },
      explore: { title: 'Explore something new', body: 'You\u2019ve got momentum. Here\u2019s a topic you haven\u2019t opened yet, ready in a few minutes.', cta: 'Explore' },
      learning: { title: 'Deepen what you know', body: 'You\u2019ve explored a lot. The Learning Center gathers the ideas behind it all in one calm place.', cta: 'Open the Learning Center' },
    },
    cards: {
      checkup: { title: 'Financial Wellness Checkup', tagline: 'A gentle two-minute snapshot of where you stand — the roadmap starts here.', minutes: 2 },
      learning: { title: 'Learning Center', tagline: 'Behavioral insights, common mistakes, and the ideas behind it all.' },
      roadmap: { title: 'Your Roadmap', tagline: 'Everything you explore gathers here into a path that\u2019s yours.' },
    },
  },
  ko: {
    eyebrow: '컴패니언 허브',
    title: '내 돈을 이해하는, 더 차분한 방법.',
    sub: '끝내야 할 긴 설문은 없어요. 각각 몇 분이면 되는 짧고 정직한 주제들을 탐색하면 — 당신과 함께 조용히 자라는 로드맵이 생겨요.',
    trust: '언제나 교육 목적입니다. 상품을 팔지 않고, 어떤 것도 기기를 떠나지 않아요.',
    todaysLessonLabel: '오늘의 배움',
    todaysTipLabel: '오늘의 컴패니언 팁',
    nextStepLabel: '추천 다음 단계',
    exploreLabel: '주제 탐색하기',
    toolsLabel: '나의 동반자',
    minutesLabel: '분',
    exploreCta: '탐색',
    exploredBadge: '탐색함',
    startCta: '시작',
    lessons: [
      { title: '현금 흐름은 점수판이 아니라 이야기예요.', body: '모든 계획은 그저 돈이 어디로 흐르는지 보는 데서 시작해요 — 먼저 강점을, 그리고 손볼 만한 한두 빈틈을 찾으려고요.' },
      { title: '대개 타이밍보다 시간이 이겨요.', body: '은퇴 저축에선, 얼마나 영리한가보다 돈이 얼마나 오래 자라는가가 더 중요해요. 일찍 작게 시작하는 쪽이 이기곤 하죠.' },
      { title: '불편이 아니라 재앙에 대비하세요.', body: '보험은 스스로 감당 못 할 손실을 위한 것 — 그 목록은 삶이 변하면 조용히 함께 변해요.' },
      { title: '환급은 상이 아니에요.', body: '큰 세금 환급은 대개 내 돈을 늦게 돌려받는 것뿐이에요. 봄의 깜짝 선물보다 연중 꾸준한 감각이 나아요.' },
      { title: '학자금은 빌릴 수 있어도, 은퇴는 빌릴 수 없어요.', body: '사랑하는 부모는 흔히 교육을 먼저 챙기지만, 대개 튼튼한 토대가 먼저예요. 순서가 중요해요.' },
      { title: '걱정에 이름을 붙이면 작아져요.', body: '돈 스트레스는 미덕이 아니라 불확실성을 따라와요. 자책이 아니라 또렷함과 작은 걸음으로 누그러집니다.' },
    ],
    tips: [
      '오늘 지출 하나를 살펴보세요 — 판단 없이, 그저 보기만요. 알아차림이 모든 계획의 시작이에요.',
      '월급 받는 날, 무엇보다 먼저 작은 금액을 저축으로 옮기세요. 쓰기 전에 저축해야 이뤄져요.',
      '가진 보험 하나가 실제로 무엇을 보장하는지 읽어 보세요. 이해가 가입을 이겨요.',
      '나에게 어떤 은퇴 제도가 있는지 알아보세요. 아는 것이 첫걸음이에요.',
      '큰 지출은 하룻밤 자고 결정하세요. 미래의 내가 대개 고마워해요.',
      '가장 큰 돈 걱정을 한 번 소리 내어 말해 보세요. 이름이 붙으면 조금 작아져요.',
    ],
    next: {
      checkup: { title: '먼저 방향을 잡아요', body: '부드러운 2분 체크업이 로드맵의 출발점을 만들어 줘요 — 부담 없이, 기기를 벗어나 저장되는 것도 없이요.', cta: '체크업 해보기' },
      explore: { title: '새로운 것을 탐색해요', body: '흐름을 타고 있네요. 아직 열지 않은 주제가 여기 있어요, 몇 분이면 돼요.', cta: '탐색하기' },
      learning: { title: '아는 것을 더 깊게', body: '많이 탐색했어요. 러닝 센터가 그 뒤의 생각들을 한 곳에 차분히 모아 둡니다.', cta: '러닝 센터 열기' },
    },
    cards: {
      checkup: { title: '재정 건강 체크업', tagline: '지금 어디에 서 있는지 부드러운 2분 스냅샷 — 로드맵이 여기서 시작돼요.', minutes: 2 },
      learning: { title: '러닝 센터', tagline: '행동 인사이트, 흔한 실수, 그리고 그 뒤의 생각들.' },
      roadmap: { title: '나의 로드맵', tagline: '탐색한 모든 것이 나만의 길로 이곳에 모여요.' },
    },
  },
}
